Новая диагностика: экспортные методы в модулях команд
1c-syntax/bsl-language-server pull request #1393
Opened 2020-10-05 17:11 UTC by akabrr

## Описание
Добавлена новая диагностика: экспортные методы в модулях команд

## Связанные задачи

Closes:

## Чеклист

### Общие

- [X] Ветка PR обновлена из develop
- [X] Отладочные, закомментированные и прочие, не имеющие смысла участки кода удалены
- [X] Изменения покрыты тестами
- [X] Обязательные действия перед коммитом выполнены (запускал команду `gradlew precommit`)

### Для диагностик

- [X] Описание диагностики заполнено для обоих языков (перевод на английский не обязателен)

## Дополнительно

2020-10-05 17:52 UTC, asosnoviy approved these changes
Огонь!

2020-10-05 17:55 UTC, asosnoviy commented on src/main/resources/com/github/_1c_syntax/bsl/languageserver/diagnostics/CommandModuleExportMethodsDiagnostic_ru.properties
> +diagnosticName=Экспортные процедуры и функции в модулях команд и общих команд
Вместо `процедуры и функции` - методы

2020-10-05 18:16 UTC, asosnoviy commented on src/main/resources/com/github/_1c_syntax/bsl/languageserver/diagnostics/CommandModuleExportMethodsDiagnostic_ru.properties
> +diagnosticName=Экспортные процедуры и функции в модулях команд и общих команд
Экспортные методы в модулях команд

2020-10-06 09:56 UTC, nixel2007 requested changes
.

2020-10-06 09:56 UTC, nixel2007 commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/CommandModuleExportMethodsDiagnostic.java
> +      diagnosticStorage.addDiagnostic(method.getRange());
Кажется, здесь стоит передать subNameRange, чтобы не засветить весь километровый метод целиком.

2020-10-06 16:18 UTC, akabrr commented
Жутко интересно, поэтому я за любые изменения

2020-10-06 16:23 UTC, asosnoviy commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/CommandModuleExportMethodsDiagnostic.java
> +      diagnosticStorage.addDiagnostic(method.getRange());
@akabr ты можешь собрать jar положить его в vsc и сразу поймешь что не так

2020-10-07 14:47 UTC, nixel2007 commented
Супер, спасибо большое! Добро пожаловать в клуб :)

2020-10-07 14:47 UTC, merged

2020-10-23 20:50 UTC, EightM commented
FP на обработчиках оповещения расположенных в модуле команды не будет? (:

2020-10-24 09:02 UTC, nixel2007 commented
Может быть. но в теории это можно все обработать, проверив конструкторы описаний оповещений и сложив их в set.