Добавил исключение для метода БСП - ФайловаяСистема.УдалитьВременныйФайл
1c-syntax/bsl-language-server pull request #1447
Opened 2020-11-13 11:27 UTC by artbear

сейчас приходится добавлять вручную в профиле качества

## Описание

## Связанные задачи

## Чеклист

### Общие

- [ ] Ветка PR обновлена из develop
- [ ] Отладочные, закомментированные и прочие, не имеющие смысла участки кода удалены
- [ ] Изменения покрыты тестами
- [ ] Обязательные действия перед коммитом выполнены (запускал команду `gradlew precommit`)

### Для диагностик

- [ ] Описание диагностики заполнено для обоих языков (перевод на английский не обязателен)

## Дополнительно

2020-11-13 11:49 UTC, nixel2007 commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/MissingTemporaryFileDeletionDiagnostic.java
> +  public static final String REGEX_DELETION_FILE = "УдалитьФайлы|DeleteFiles|ПереместитьФайл|MoveFile|УдалитьВременныйФайл";
не вижу ничего про ФайловаяСистема :)

2020-11-13 14:53 UTC, artbear commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/MissingTemporaryFileDeletionDiagnostic.java
> +  public static final String REGEX_DELETION_FILE = "УдалитьФайлы|DeleteFiles|ПереместитьФайл|MoveFile|УдалитьВременныйФайл";
не стал усложнять регулярку, вместо ФайловаяСистема.УдалитьВременныйФайл оставил просто УдалитьВременныйФайл

имя метода очень конкретно и вполне подходит под исключение.

2020-11-13 14:54 UTC, nixel2007 commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/MissingTemporaryFileDeletionDiagnostic.java
> +  public static final String REGEX_DELETION_FILE = "УдалитьФайлы|DeleteFiles|ПереместитьФайл|MoveFile|УдалитьВременныйФайл";
допустим. а тесты? :)

2020-11-13 16:11 UTC, artbear commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/MissingTemporaryFileDeletionDiagnostic.java
> +  public static final String REGEX_DELETION_FILE = "УдалитьФайлы|DeleteFiles|ПереместитьФайл|MoveFile|УдалитьВременныйФайл";
1 я прямо из интерфейса гитхаба сделал максимально быстрый и простой ПР. явно ничего не поломал, линия сборки отработала.

2 тесты все-таки нужны не на каждый чих. существующих тестов вполне достаточно для подтверждения этого ПР.

2020-11-14 10:38 UTC, nixel2007 commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/MissingTemporaryFileDeletionDiagnostic.java
> +  public static final String REGEX_DELETION_FILE = "УдалитьФайлы|DeleteFiles|ПереместитьФайл|MoveFile|УдалитьВременныйФайл";
окей, только вот следующим рефакторингом можно эту расширенную регулярку поломать, и у клиентов высветятся тонны замечаний, т.е. произойдет регресс. скорость скоростью, качество качеством.

2020-11-14 10:49 UTC, asosnoviy commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/MissingTemporaryFileDeletionDiagnostic.java
> +  public static final String REGEX_DELETION_FILE = "УдалитьФайлы|DeleteFiles|ПереместитьФайл|MoveFile|УдалитьВременныйФайл";
> 2 тесты все-таки нужны не на каждый чих. существующих тестов вполне достаточно для подтверждения этого ПР.

А как ты проверил что их достаточно?

2020-11-14 10:52 UTC, asosnoviy commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/MissingTemporaryFileDeletionDiagnostic.java
> +  public static final String REGEX_DELETION_FILE = "УдалитьФайлы|DeleteFiles|ПереместитьФайл|MoveFile|УдалитьВременныйФайл";
Посмотрел по диагонали, но не уверен что этого дополнения достаточно.

2020-11-14 10:53 UTC, asosnoviy requested changes
Без теста не понятно является ли этот фикс -фиксом

2020-11-16 05:33 UTC, theshadowco commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/MissingTemporaryFileDeletionDiagnostic.java
> +  public static final String REGEX_DELETION_FILE = "УдалитьФайлы|DeleteFiles|ПереместитьФайл|MoveFile|УдалитьВременныйФайл";
я за либо за полное указание метода, раз это БСП, либо нафиг. Ну и явный тест тоже хочется увидеть

2020-11-16 05:37 UTC, theshadowco commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/MissingTemporaryFileDeletionDiagnostic.java
> +  public static final String REGEX_DELETION_FILE = "УдалитьФайлы|DeleteFiles|ПереместитьФайл|MoveFile|УдалитьВременныйФайл";
и еще, если я не ошибаюсь, работает только на глобальных методах
```
 public ParseTree visitGlobalMethodCall(BSLParser.GlobalMethodCallContext ctx)
```

2020-11-16 06:17 UTC, asosnoviy commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/MissingTemporaryFileDeletionDiagnostic.java
> +  public static final String REGEX_DELETION_FILE = "УдалитьФайлы|DeleteFiles|ПереместитьФайл|MoveFile|УдалитьВременныйФайл";
> и еще, если я не ошибаюсь, работает только на глобальных методах
> 
> ```
>  public ParseTree visitGlobalMethodCall(BSLParser.GlobalMethodCallContext ctx)
> ```

Ну про то и спич =)

2020-11-25 11:26 UTC, artbear commented
На днях у нас в коде встретился глобальный метод УдалитьВременныйФайл, ПР под него подходит )

2020-11-25 14:01 UTC, theshadowco commented
увы, но нет

2020-11-28 13:57 UTC, closed without merging