Улучшение RefOveruseDiagnostic
1c-syntax/bsl-language-server pull request #1532
Opened 2021-01-23 18:54 UTC by ovcharenko-di

## Описание
Расширил условия, проверяющие избыточность использования "Ссылка".
Немного отрефакторил код диагностики. 

## Связанные задачи
Closes #1530 

## Чеклист

### Общие

- [x] Ветка PR обновлена из develop
- [x] Отладочные, закомментированные и прочие, не имеющие смысла участки кода удалены
- [x] Изменения покрыты тестами
- [x] Обязательные действия перед коммитом выполнены (запускал команду `gradlew precommit`)

### Для диагностик

- [x] Описание диагностики заполнено для обоих языков (перевод на английский не обязателен)

2021-01-23 20:16 UTC, nixel2007 commented
@EightM please review

2021-01-23 20:34 UTC, EightM commented
@nixel2007 
1. Если предпоследний элемент удовлетворяет паттерну "ссылка", он по определению не может быть в множестве источников. Я бы вынес это условие из внутреннего во внешнее, на первое место, для короткой проверки.
2. Не фанат переноса тела функции обратно во вложенный if

2021-01-26 10:56 UTC, artbear commented
@ovcharenko-di еще бы проверить `.Ссылка.` в условиях соединения

2021-01-26 11:21 UTC, ovcharenko-di commented
@artbear , ага, точно! Еще диагностика пока не срабатывает на такие выражения:

```bsl
ВЫРАЗИТЬ(&Контрагент КАК Справочник.Контрагенты).Ссылка.ЮрФизЛицо
```
В доработанной ERP не могу примеров найти, однако, ситуация вполне реальная, учитывая сложность выражения.

2021-02-13 08:36 UTC, nixel2007 commented
@ovcharenko-di будешь пытаться еще доделать что-то? посмотришь замечания от @EightM ?

2021-02-15 10:33 UTC, ovcharenko-di commented
@nixel2007 , да, скоро переделаю немного по замечаниям, нового пока не буду добавлять.

2021-04-04 11:45 UTC, nixel2007 commented
kindly ping

2021-04-09 07:09 UTC, nixel2007 requested changes
Последняя защитная проверка, а в остальном все хорошо!

2021-04-09 07:09 UTC, nixel2007 commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/RefOveruseDiagnostic.java
> +    var lastChild = ctx.getChild(childCount - 1);
Давай перед этим обращением добавим проверку, что childCount >= 3.
У нас может быть `select *`, текст запроса может набираться прямо сейчас и/или запрос валиден синтаксически, но не валиден логически (выбрать ссылка из соединения двух справочников)

2021-04-09 20:16 UTC, ovcharenko-di commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/RefOveruseDiagnostic.java
> +    var lastChild = ctx.getChild(childCount - 1);
добавил проверку и заодно тест, в котором без этой проверки появляется NPE

2021-04-09 21:06 UTC, nixel2007 approved these changes

2021-04-09 21:06 UTC, merged