Новый пункт- Изменяемые java-файлы отформатированы
1c-syntax/bsl-language-server pull request #1566
Opened 2021-02-23 13:52 UTC by artbear

## Описание

## Связанные задачи

Closes: -

## Чеклист

### Общие

- **правка в веб-интерфейсе гитхаба**

- [x] Ветка PR обновлена из develop
- [x] Отладочные, закомментированные и прочие, не имеющие смысла участки кода удалены
- [x] Изменения покрыты тестами
- [ ] Обязательные действия перед коммитом выполнены (запускал команду `gradlew precommit`)

### Для диагностик

- [ ] Описание диагностики заполнено для обоих языков (перевод на английский не обязателен)

## Дополнительно

2021-02-23 13:53 UTC, artbear commented
При работе над https://github.com/1c-syntax/bsl-language-server/pull/1556#discussion_r580760243 обнаружили, что модуль не отформатирован.

Предлагаю добавить пункт в чек-лист для улучшения

2021-02-23 14:45 UTC, nixel2007 commented
meh, оно должно орать само. может в настройки проекта (идея-файлы) добавить пункт с автоформатом для джава-кода? ну или в editorconfig, он же для этого как раз.

2021-02-23 15:58 UTC, artbear commented
Ну да, тогда лучше и добавить.
но я не знаю как )

2021-02-23 16:07 UTC, nixel2007 commented
Настройки эдитор конфига лежат в корне репы :)

2021-03-01 07:59 UTC, theshadowco commented
я против доработок шаблона... давайте файл с настройками этитора и усе

2021-03-02 13:00 UTC, nixel2007 requested changes
Использование editor config

2021-03-21 10:59 UTC, theshadowco commented
editor config отдельным реквестом, а этот закрываю, а плесенью покрылся

2021-03-21 10:59 UTC, closed without merging