Feature/set permissions for new objects
1c-syntax/bsl-language-server pull request #1688
Opened 2021-06-13 18:10 UTC by EvgSychev

## Описание
Добавлена диагностика SetPermissionsForNewObjectsDiagnostic

## Связанные задачи

Closes: #1280 

## Чеклист

### Общие

- [X] Ветка PR обновлена из develop
- [X] Отладочные, закомментированные и прочие, не имеющие смысла участки кода удалены
- [X] Изменения покрыты тестами
- [X] Обязательные действия перед коммитом выполнены (запускал команду `gradlew precommit`)

### Для диагностик

- [ X] Описание диагностики заполнено для обоих языков (перевод на английский не обязателен)

## Дополнительно

2021-06-14 06:59 UTC, otymko requested changes

2021-06-14 06:59 UTC, otymko commented on .idea/compiler.xml
>      </annotationProcessing>
@EvgSychev откатить изменение файла

2021-06-14 06:59 UTC, otymko commented on bsl-junit.xml
> +<testsuites name="bsl-language-server">
@EvgSychev откатить этот файл

2021-06-14 06:59 UTC, otymko commented on docs/diagnostics/SetPermissionsForNewObjects.md
> +# <Имя диагностики> (SetPermissionsForNewObjects)
@EvgSychev что-то с заголовком диагностики

2021-06-14 06:59 UTC, otymko commented on genericCoverage.xml
> +<coverage version="1">
@EvgSychev откатить этот файл

2021-06-14 06:59 UTC, otymko commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/SetPermissionsForNewObjectsDiagnostic.java
> +    {
@EvgSychev открытие скобки не должно быть на новой строке

2021-06-14 06:59 UTC, otymko commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/SetPermissionsForNewObjectsDiagnostic.java
> +    for (var role : roles)
@EvgSychev можно заменить на стрим, но это не обязательно.

2021-06-14 06:59 UTC, otymko commented on src/main/resources/com/github/_1c_syntax/bsl/languageserver/diagnostics/SetPermissionsForNewObjectsDiagnostic_en.properties
> +diagnosticMessage=<Message>
@EvgSychev Заполнить сообщение и имя проверки на English

2021-06-14 06:59 UTC, otymko commented on src/main/resources/com/github/_1c_syntax/bsl/languageserver/diagnostics/SetPermissionsForNewObjectsDiagnostic_ru.properties
> +diagnosticMessage=<Сообщение>
@EvgSychev Заполнить сообщение и имя проверки на Russian

2021-06-14 06:59 UTC, otymko commented on src/test/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/SetPermissionsForNewObjectsDiagnosticTest.java
> +  private static final String PATH_TO_METADATA = "src/test/resources/metadata";
@EvgSychev выше конструктора

2021-06-14 06:59 UTC, otymko commented on src/test/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/SetPermissionsForNewObjectsDiagnosticTest.java
> +      List<Diagnostic> diagnostics = getDiagnostics();
@EvgSychev `List<Diagnostic>` -> `var`

2021-06-14 15:18 UTC, nixel2007 commented
Перебазировал ветку и немного доработал. Спасибо за пулл-реквест!

На будущее - синхронизируйте, пожалуйста, свой девелоп с девелопом из 1c-syntax жестко, через git reset --hard, а не мерж-реквестом. это позволит избежать мусорных коммитов в истории

2021-06-14 15:22 UTC, nixel2007 commented
@otymko @theshadowco @asosnoviy у меня другой вопрос... почему тест зеленый? почему на UNKNOWN-модуль сработала диагностика, которая должна была вешаться исключительно на модуль упр. приложения? без всякий spy/mock и прочего

2021-06-14 15:52 UTC, otymko commented
@nixel2007 не совсем понял вопроса. Диагностика сработала на модуль упр. приложения из каталога с метаданными (конфигурацией). То что создан модуль для диагностики - это просто заглушка. Но ручками я не проверял

2021-06-14 19:35 UTC, nixel2007 commented
@otymko в диагностику передаётся текущий документ контекст. Хотя наверное в этом и ответ - фильтрация же производится уровнем выше

2021-06-15 04:28 UTC, theshadowco commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/SetPermissionsForNewObjectsDiagnostic.java
> +  private static final String NAME_FULL_ACCESS_ROLE_RU = "ПолныеПрава";
Сделай пож-ста параметром имя роли с полными правами (список строкой через запятую)

2021-06-15 17:00 UTC, EvgSychev commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/SetPermissionsForNewObjectsDiagnostic.java
> +  private static final String NAME_FULL_ACCESS_ROLE_RU = "ПолныеПрава";
Принято

2021-06-15 18:45 UTC, EvgSychev commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/SetPermissionsForNewObjectsDiagnostic.java
> +  private static final String NAME_FULL_ACCESS_ROLE_RU = "ПолныеПрава";
Может лучше два параметра? Список строкой придётся разделять в массив и обращаться по индексу к подстрокам, чтобы обеспечить точность сравнения имени роли. Можем упасть с неинформативной ошибкой если ошиблись с текстом параметра.

2021-06-15 18:53 UTC, EvgSychev commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/SetPermissionsForNewObjectsDiagnostic.java
> +  private static final String NAME_FULL_ACCESS_ROLE_RU = "ПолныеПрава";
Сделаю через вхождение в массив.

2021-06-16 06:39 UTC, EvgSychev commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/SetPermissionsForNewObjectsDiagnostic.java
> +  private final String[] namesFullAccessRole = NAMES_FULL_ACCESS_ROLE.split(",");
> Может лучше ввести новый филд roleNames с типом Set<String>? Тогда в check можно будет написать:
Predicate.not(roleNames::contains).

Согласен, так будет лучше

2021-06-16 06:39 UTC, EvgSychev commented on src/test/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/SetPermissionsForNewObjectsDiagnosticTest.java
>    void test() {
Добавлю

2021-06-16 06:41 UTC, EvgSychev commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/SetPermissionsForNewObjectsDiagnostic.java
> +  private final String[] namesFullAccessRole = NAMES_FULL_ACCESS_ROLE.split(",");
Configure по мануалу требуется, я когда этот код писал ещё не успел прочитать пункт про параметры :)

2021-06-20 06:00 UTC, otymko approved these changes

2021-06-20 18:11 UTC, merged

2021-06-20 18:11 UTC, nixel2007 commented
Спасибо!