Исключаю из покрытия несущественные строки
1c-syntax/bsl-language-server pull request #1697
Opened 2021-06-19 12:37 UTC by artbear

## Описание

Исключаю из покрытия несущественные строки
- Строки для препроцессора
- Перем
- КонецХХХ
- Попытка, Исключение

Также дополнил тесты

## Связанные задачи

Closes #1089

## Чеклист

### Общие

- [x] Ветка PR обновлена из develop
- [x] Отладочные, закомментированные и прочие, не имеющие смысла участки кода удалены
- [x] Изменения покрыты тестами
- [ ] Обязательные действия перед коммитом выполнены (запускал команду `gradlew precommit`)

### Для диагностик

- [ ] Описание диагностики заполнено для обоих языков (перевод на английский не обязателен)

## Дополнительно

2021-06-19 13:01 UTC, artbear commented
Благодаря такой реализации мы всегда показываем одинаковый набор строк.

инструменты, которые получают замеры. должны использовать этот набор 

и исключать те строки, которых нет в данном наборе, 
т.к. эти строки несущественны для целей покрытия.

например, coverage41c или coverage-cli

2021-06-19 13:20 UTC, artbear commented
Описание ПР было неточно - я не убираю поддержку КонецХХХ, т.к. этой поддержки и так нет )

2021-06-22 12:08 UTC, asosnoviy commented
Пока мне кажется что это исправлено в Coverage41C и там ему и место.
https://github.com/1c-syntax/Coverage41C/blob/master/src/main/java/com/clouds42/Utils.java#L186

2021-06-22 12:41 UTC, asosnoviy requested changes
Расчет к покрытию уехал в Coverage41C

2021-06-24 12:15 UTC, artbear commented
в итоге аналогичный ПР https://github.com/1c-syntax/Coverage41C/pull/108

2021-06-24 13:12 UTC, closed without merging