LatinAndCyrillicSymbolInWordDiagnostic
1c-syntax/bsl-language-server pull request #1713
Opened 2021-06-29 14:05 UTC by theshadowco

## Описание

Добавлен параметр (включен по умолчанию) для отключения шупа на идентификаторах начинающихся либо заканчивающихся словами иного языка

## Связанные задачи

Closes: #1684

## Чеклист

### Общие

- [x] Ветка PR обновлена из develop
- [x] Отладочные, закомментированные и прочие, не имеющие смысла участки кода удалены
- [x] Изменения покрыты тестами
- [x] Обязательные действия перед коммитом выполнены (запускал команду `gradlew precommit`)

### Для диагностик

- [ ] Описание диагностики заполнено для обоих языков (перевод на английский не обязателен)

## Дополнительно

2021-06-30 07:16 UTC, asosnoviy commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/LatinAndCyrillicSymbolInWordDiagnostic.java
> +  private static final int MINIMAL_WORD_LEN_TWO_LANG = 4;
👍

2021-06-30 12:17 UTC, artbear requested changes

2021-06-30 12:17 UTC, artbear commented on docs/diagnostics/LatinAndCyrillicSymbolInWord.md
> +Для снижения "шума" на именах состоящих из нескольких слов, начинающихся либо заканчивающихся на слово на другом языке в диагностику добавлен параметр, включенный по умолчанию.
после "на другом языке" нужна запятая

2021-07-01 18:16 UTC, nixel2007 commented on docs/diagnostics/LatinAndCyrillicSymbolInWord.md
> +Для снижения "шума" на именах состоящих из нескольких слов, начинающихся либо заканчивающихся на слово на другом языке в диагностику добавлен параметр, включенный по умолчанию.
```suggestion
Для снижения "шума" на именах состоящих из нескольких слов, начинающихся либо заканчивающихся на слово на другом языке, в диагностику добавлен параметр, включенный по умолчанию.  
```

2021-07-01 18:19 UTC, nixel2007 commented
@theshadowco ребейзни поверх нового прекоммита, плз.

2021-07-01 18:35 UTC, asosnoviy commented
Ребейзнул

2021-07-01 19:14 UTC, merged

2021-07-01 19:16 UTC, nixel2007 commented
@asosnoviy блин, а прекоммит-то, прекоммит) новый параметр добавился, он же должен лечь в таблицу параметров