Диагностика поска запрещенных слов
1c-syntax/bsl-language-server pull request #1771
Opened 2021-09-01 06:43 UTC by Golovanoff

## Описание
ищет указанные в параметре диагностики слова во всех строках модулей,  независимо от того, что это - комментарий или нет.

## Связанные задачи

Closes: не делал

## Чеклист

### Общие

- [ ] Ветка PR обновлена из develop
- [ ] Отладочные, закомментированные и прочие, не имеющие смысла участки кода удалены
- [ ] Изменения покрыты тестами
- [ ] Обязательные действия перед коммитом выполнены (запускал команду `gradlew precommit`)

### Для диагностик

- [ ] Описание диагностики заполнено для обоих языков (перевод на английский не обязателен)

## Дополнительно

2021-09-01 07:31 UTC, artbear commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/BadWordsDiagnostic.java
> +    String[] moduleLines = documentContext.getContent().split("\n");
ну такое, перебор абсолютно всех строк модулей, неважно, служебные ключевые слова 1с или что другое (

2021-09-01 07:33 UTC, artbear requested changes
Нет разделения ни на строки-комментарии, ни на строки кода.
Зачем анализировать строки с ключевыми словами, которые явно не подойдут под правило - Если, КонецХХХ, Попытка, Исключение и т.п.

2021-09-01 07:55 UTC, nixel2007 commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/BadWordsDiagnostic.java
> +    Pattern pattern = CaseInsensitivePattern.compile(badWords);
можно паттерн сохранить прямо в поле, являющееся параметром. посмотри пример в LatinAndCyrillicSymbolInWordDiagnostic - как там идет работа с этим полем и обработка вызова метода configure.

2021-09-01 07:56 UTC, nixel2007 commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/BadWordsDiagnostic.java
> +    String[] moduleLines = documentContext.getContent().split("\n");
вместо сплита (который в ряде случаев может работать не так, как ты ожидаешь, и выдавать некорректные номера строк) стоит вызвать documentContext.getContentList()

2021-09-01 07:57 UTC, nixel2007 commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/BadWordsDiagnostic.java
> +  protected void check() {
кажется имеет смысл проверить, что паттерн не пустой. ведь пустая регулярка никогда ничего не вернет, но при этом каждый раз будет пытаться выполнить поиск ничего по каждой строке

2021-09-01 07:58 UTC, nixel2007 commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/BadWordsDiagnostic.java
> +    for (int i=0; i<moduleLines.length; i++ ) {
ctrl-alt-L спасет отца русской демократии! :)

2021-09-01 07:59 UTC, nixel2007 commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/BadWordsDiagnostic.java
> +      Matcher matcher = pattern.matcher(moduleLines[i]);
может быть вместо построчного перебора файла добавить регулярке флаг MULTILINE? тогда она сможет обрабатывать весь файл за один проход. экономия на создании матчера. но возможно чуть сложнее будет искать положение в файле (за счет оффсета)

2021-09-01 08:00 UTC, nixel2007 commented on src/main/resources/com/github/_1c_syntax/bsl/languageserver/diagnostics/BadWordsDiagnostic_ru.properties
> +diagnosticMessage=В тексте модуля найдено запрещенное слово
имеет смысл добавить запрещенное слово в параметр сообщения через %s и передачу в метод получения сообщения (`info.getMessage()`)

2021-09-01 08:02 UTC, nixel2007 commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/BadWordsDiagnostic.java
> +import com.github._1c_syntax.utils.*;
star-import надо заменить на точечное указание.

2021-09-01 08:05 UTC, nixel2007 commented
@artbear 

> Нет разделения ни на строки-комментарии, ни на строки кода.

а какая разница? запрещенное слово есть запрещенное слово.

> Зачем анализировать строки с ключевыми словами, которые явно не подойдут под правило - Если, КонецХХХ, Попытка, Исключение и т.п.

как ты это предлагаешь реализовывать? через простыню условий в регулярке, все десятки слов на двух языках? Кается, что это будет дороже, чем выполнить саму проверку.

2021-09-01 08:06 UTC, nixel2007 commented
@Golovanoff не хватает markdown-ресурсов диагностики. и нужно выполнить gradle-команду precommit, чтобы обновить индекс диагностик и json-схему.

2021-09-01 14:54 UTC, artbear commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/BadWordsDiagnostic.java
> +      Matcher matcher = pattern.matcher(moduleLines[i]);
да, режим MULTILINE и поиск для всего файла д.б. побыстрее

2021-09-01 14:55 UTC, artbear commented on src/main/resources/com/github/_1c_syntax/bsl/languageserver/diagnostics/BadWordsDiagnostic_ru.properties
> +badWords=Запрещенные слова
"и вообще это часть регулярки" - расшифровать, что нужно экранировать служебные символы регулярок, например, знак плюс или точка или скобка и т.п.

2021-09-03 19:05 UTC, nixel2007 commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/BadWordsDiagnostic.java
> +    int lineNum = StringUtils.countMatches(textBefore, "\n");
будет врать при одиночных CR

2021-09-03 19:08 UTC, nixel2007 commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/BadWordsDiagnostic.java
> +    int lineNum = StringUtils.countMatches(textBefore, "\n");
надо попробовать через вот эту штуку. возможно стоит добавить метод прям в документ-контекст.

https://docs.oracle.com/javase/7/docs/api/java/io/LineNumberReader.html

2021-09-04 05:33 UTC, Golovanoff commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/BadWordsDiagnostic.java
> +    int lineNum = StringUtils.countMatches(textBefore, "\n");
> будет врать при одиночных CR

у меня 2 и 8 строки - только переводы строк. нормально вроде обрабатываются
или ты про маздайные концы строк?

2021-09-04 10:31 UTC, nixel2007 commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/BadWordsDiagnostic.java
> +    int lineNum = StringUtils.countMatches(textBefore, "\n");
Про макосные (просто cr вместо lf или cr+lf). Конфигуратор их нормально рисует, а все современные среды сходят с ума.

2021-09-16 09:16 UTC, artbear commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/BadWordsDiagnostic.java
> +    DiagnosticTag.DESIGN
почему тег DESIGN
тег Подозрительный лучше подходит

2021-09-16 09:29 UTC, artbear requested changes

2021-09-16 09:29 UTC, artbear commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/BadWordsDiagnostic.java
> +    String moduleText = String.join("\n", documentContext.getContentList());
а почему не сразу getContent() ?
зачем лишние вычисления?

ведь getContentList() и получается из content внутри DocumentContext

2021-09-16 09:29 UTC, artbear commented on src/main/resources/com/github/_1c_syntax/bsl/languageserver/diagnostics/BadWordsDiagnostic_ru.properties
> +diagnosticMessage=В тексте модуля найдено запрещенное слово %s
Предлагаю использовать побудительное предложение.

например, Исправьте запрещенное слово %s

2021-09-16 09:29 UTC, artbear commented on src/test/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/BadWordsDiagnosticTest.java
> +    assertThat(diagnostics).hasSize(0); // Проверка количества
Предлагаю комментарий удалить и переназвать тест.

например, testWithoutRegExpForBadWords

2021-09-16 09:29 UTC, artbear commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/BadWordsDiagnostic.java
> +    String moduleText = String.join("\n", documentContext.getContentList());
и в этом случае легко посчитать номера строк и смещение в них, т.к. и у бсл лс, и у матчера будут одинаковые строки.
@nixel2007 верно?

2021-09-16 10:16 UTC, nixel2007 commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/BadWordsDiagnostic.java
> +    String moduleText = String.join("\n", documentContext.getContentList());
там все не так очевидно, к сожалению. у матчера вообще нет "строки", у него есть позиция в символах от начала документа. в фича-бранче я начал накидывать хелперы для получения позиции и рэнжа с учетом корректного определения номеров строк, но работу еще не закончил.

2021-09-22 04:05 UTC, Golovanoff commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/BadWordsDiagnostic.java
> +    String moduleText = String.join("\n", documentContext.getContentList());
я таким образом "переложил" ответственность за концы строк на getContentList(). Моя идея в том, что getContentList() корректно разобьет на строки с учетом всех вывертов (cr, crlf или lf или что там в голову может взбрести богомерзким изобретателям нелинуксовых концов строк). А я затем снова собираю текст уже через lf и мне для расчет позиции не надо заморачиваться разными концами строк.
Это, конечно,  не сработает, если getContentList() не убирает из своих элементов концы строк.

2021-09-22 15:37 UTC, artbear commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/BadWordsDiagnostic.java
> +    String moduleText = String.join("\n", documentContext.getContentList());
@Golovanoff для производительности вредна такая повторная сборка (
представь, КАЖДЫЙ файл модуля только из-за одной этой диагностики будет заново собираться (

2021-09-23 10:50 UTC, closed without merging