Draft: ReferenceIndexFiller учитывает ОписанияОповещения
1c-syntax/bsl-language-server pull request #2797
Opened 2022-06-07 18:26 UTC by qtLex

## Описание
`ReferenceIndexFiller` доработал на добавление в `ReferenceIndex` методов используемых в `ОписанииОповещения`.
Учитывается методы указанные в успешной обработке и методы для обработки ошибок.

Обрабатывается самый простой вариант и распространенный вариант.
С остальными пока не понятно. Варианты перечислены в тестах.

Временно как черновик, хочу погонять результат в `VS Code`

## Связанные задачи

Closes #1191

## Чеклист

### Общие

- [ ] Ветка PR обновлена из develop
- [x] Отладочные, закомментированные и прочие, не имеющие смысла участки кода удалены
- [x] Изменения покрыты тестами

2022-06-07 20:13 UTC, nixel2007 commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/references/ReferenceIndexFiller.java
> +        .map(BSLParser.NewExpressionContext::typeName)
Жаль, что обработать функциональный вызов Новый() по простому не получится - там надо будет массив анализировать :(

2022-06-07 20:13 UTC, nixel2007 commented on src/test/resources/metadata/designer/Documents/Документ1/Forms/ФормаДокумента/Ext/Form/Module.bsl
> +        КлиентскийОбщийМодуль,
Или ты уже палишь общие модули? Немного потерялся в логике

2022-06-07 20:19 UTC, EightM commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/references/ReferenceIndexFiller.java
> +        if (callParamList.size() == 5) {
магические числа бы вынести

2022-06-07 20:21 UTC, EightM commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/references/ReferenceIndexFiller.java
> +        return trimLastQuote(newText).trim();
trim лучше заменить на strip

2022-06-07 20:31 UTC, qtLex commented on src/test/resources/metadata/designer/Documents/Документ1/Forms/ФормаДокумента/Ext/Form/Module.bsl
> +        КлиентскийОбщийМодуль,
Общие модули ловятся.
Модули менеджера не проверял. Они только в `Толстом клиенте` доступны на `Клиенте`. А `ОписаниеОповещения` только на клиенте существует. Но там используется тот же метод, что и при поиске модулей для простого вызова метода. Может и заработает. Проверю.

2022-06-07 20:32 UTC, qtLex commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/references/ReferenceIndexFiller.java
> +    private final Pattern THIS_OBJECT_PATTERN = CaseInsensitivePattern.compile(
Общие модули уже ловяться

2022-06-07 20:36 UTC, EightM commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/references/ReferenceIndexFiller.java
> +    private Optional<Token> getMethodName(BSLParser.CallParamContext callParamContext) {
Кажется этот метод не принадлежит классу Filler. Может это полезный утилитный метод?

2022-06-07 20:50 UTC, nixel2007 commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/references/ReferenceIndexFiller.java
> +    private Optional<Token> getMethodName(BSLParser.CallParamContext callParamContext) {
Как и с пяток соседних с тем же названием

2022-06-07 21:14 UTC, EightM commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/references/ReferenceIndexFiller.java
> +    private void addCallbackMethodCall(BSLParser.CallParamContext methodName, BSLParser.CallParamContext module) {
от CallParamContext мы всегда берем String mdoRef. Может стоит заменить сигнатуру на String moduleMdoRef?

2022-06-07 21:18 UTC, EightM commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/references/ReferenceIndexFiller.java
> +      return Optional.of(member.get(0));
```suggestion
Optional.ofNullable(callParamContext.expression())
        .map(BSLParser.ExpressionContext::member)
        .filter(Predicate.not(List::isEmpty))
        .map(member -> member.get(0));
```

2022-06-07 21:26 UTC, EightM commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/references/ReferenceIndexFiller.java
> +        });
```suggestion
getFirstMember(callParamContext)
        .map(BSLParser.MemberContext::complexIdentifier)
        .filter(Predicate.not(this::isThisObject))
        .map(complexIdentifier -> MdoRefBuilder.getMdoRef(documentContext, complexIdentifier))
        .orElse(MdoRefBuilder.getMdoRef(documentContext));
```

2022-06-07 21:28 UTC, EightM commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/references/ReferenceIndexFiller.java
> +    private String trimLastQuote(String text) {
Копипаст из QueryComputer, стоит подумать над выносом в утилитный класс

2022-06-07 21:53 UTC, EightM commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/references/ReferenceIndexFiller.java
> +    private void addCallbackMethodCall(BSLParser.CallParamContext methodName, BSLParser.CallParamContext module) {
> Не понял предложения.
Нам нужен mdoRef, а мы зачем-то просим module. Не понимаю зачем методу запрашивать объект с которым он по сути не работает. Так можно будет вынести один if наверх

2022-06-07 21:57 UTC, qtLex commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/references/ReferenceIndexFiller.java
> +      return Optional.of(member.get(0));
Перенес руками. Так как вынес в utils

2022-06-07 22:05 UTC, qtLex commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/references/ReferenceIndexFiller.java
> +        });
Тут замена получилась не правильная, так как потеряли вариант когда модуль не был найден.

2022-06-07 22:49 UTC, EightM commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/references/ReferenceIndexFiller.java
> +        });
Не понял про какой не найденный модуль речь

2022-06-08 07:43 UTC, qtLex commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/references/ReferenceIndexFiller.java
> +        });
А не все правильно. Эт я натупил

2022-06-08 07:43 UTC, qtLex commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/references/ReferenceIndexFiller.java
> +        });
Перенес руками

2022-06-08 10:22 UTC, qtLex commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/references/ReferenceIndexFiller.java
> +        if (callParamList.size() == 5) {
Вынес

2022-06-08 10:22 UTC, qtLex commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/references/ReferenceIndexFiller.java
> +        return trimLastQuote(newText).trim();
Заменил

2022-06-08 10:22 UTC, qtLex commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/references/ReferenceIndexFiller.java
> +    private Optional<Token> getMethodName(BSLParser.CallParamContext callParamContext) {
Вынес

2022-06-08 10:23 UTC, qtLex commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/references/ReferenceIndexFiller.java
> +    private void addCallbackMethodCall(BSLParser.CallParamContext methodName, BSLParser.CallParamContext module) {
Сделал

2022-06-08 10:23 UTC, qtLex commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/references/ReferenceIndexFiller.java
> +    private String trimLastQuote(String text) {
Вынес

2022-06-08 13:49 UTC, artbear commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/utils/Strings.java
> +  }
метод trimLastQuote неверно работает или не соответствует своему названию.
![image](https://user-images.githubusercontent.com/2920817/172633282-7c910ed2-1e30-44c7-84de-c3dc0a2bdd23.png)

2022-06-08 13:53 UTC, artbear requested changes

2022-06-08 13:53 UTC, artbear commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/utils/Strings.java
> +  }
похоже, что и trimQuotes также не соответствует своему названию или ошибка в реализации

![image](https://user-images.githubusercontent.com/2920817/172634001-8c5c26ca-3a44-4af3-8556-668c244d4e63.png)

2022-06-09 22:16 UTC, qtLex commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/utils/Strings.java
> +  }
Тут все переписал. Думаю более не актуально.

2022-06-09 22:35 UTC, qtLex commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/references/ReferenceIndexFiller.java
>        for (Map.Entry<ModuleType, URI> e : modules.entrySet()) {
Переделал

2022-07-05 08:38 UTC, merged