Новое правило - Обращение к отсутствующему методу общего модуля MissingCommonModuleMethod
1c-syntax/bsl-language-server pull request #2827
Opened 2022-06-26 20:59 UTC by artbear

## Описание

- реализация правила
- обработка исключений
- проверка на БСП 3.1, БСП 3.0 с доработками и КА 2.5 с доработками 

## Связанные задачи

Closes #995

## Чеклист

### Общие

- [x] Ветка PR обновлена из develop
- [x] Отладочные, закомментированные и прочие, не имеющие смысла участки кода удалены
- [x] Изменения покрыты тестами
- [x] Обязательные действия перед коммитом выполнены (запускал команду `gradlew precommit`)

### Для диагностик

- [x] Описание диагностики заполнено для обоих языков (присутствуют файлы для обоих языков, для русского заполнено все подробно, перевод на английский можно опустить)

## Дополнительно

2022-06-27 21:15 UTC, nixel2007 commented
Блин, а зачем так сложно-то? Ты по сути повторил работу референс индекс филлера. Хрен с ним с апи, давай просто заинжектим символьный репозиторий и ты попробуешь разрезолвить все mdoRef и их методы.

2022-06-28 07:16 UTC, asosnoviy commented
а я не понял почему только общие модули?

2022-06-28 08:06 UTC, nixel2007 commented
модули менеджера еще можно. для остального нужен тайп резолвер

2022-06-28 12:04 UTC, artbear commented
Еще раз проверю работу реф.индекса для общих модулей и модулей менеджеров.
- что-то у меня не получилось с ними, использовал почти обычный вариант.
- он не сложный, просто разбор имени и все.

2022-07-01 14:46 UTC, artbear commented
Запуши исправления правила, но найден баг https://github.com/1c-syntax/bsl-language-server/issues/2832

Перевел в WIP, пока баг не будет решен

2022-07-03 16:07 UTC, artbear commented
После вливания исправительного ПР https://github.com/1c-syntax/bsl-language-server/pull/2833 это правило проходит тесты!

2022-07-03 17:12 UTC, artbear commented
Даже после вливания исправительного ПР https://github.com/1c-syntax/bsl-language-server/pull/2833 это правило не проходит тесты!
т.к. нельзя получить ссылки на приватные методы общих модулей и менеджеров объектов через ReferenceIndex.getReferencesXXX

проблему я зафиксировал в https://t.me/bsl_language_server/98986

Предложение - проверку приватности символа лучше не закрывать внутри реф.индекса, а отдать наружу для клиента
например, в класс Reference добавить спец.поле isAccessible

пусть клиенты решают

моему правилу без этого фичу с ошибочным приватным вызовом не решить (
или придется влезать во внутренности реф.индекса и через спринг добывать locationRepository или symbolOccurrenceRepository
ведь в них-то инфа хранится ))

2022-09-25 10:51 UTC, artbear commented
@theshadowco @nixel2007 правило готово. примите его, если нет возражений.

2022-10-16 17:54 UTC, otymko requested changes

2022-10-16 17:54 UTC, otymko commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/MissingCommonModuleMethodDiagnostic.java
> +  minutesToFix = 1,
@artbear явно, не 1 минута..

2022-10-16 17:54 UTC, otymko commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/MissingCommonModuleMethodDiagnostic.java
> +  private static class CallData {
@artbear, класс читается лучше, если иннер классы находятся после методов экземпляра класса.

2022-10-16 17:54 UTC, otymko commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/MissingCommonModuleMethodDiagnostic.java
> +      // TODO какие еще типы модулей поддержать? модули менеджеров - путаница с платформенными методами, без контекста не решить
@artbear, не плохо было бы повесить issue на TODO и сразу его писать сюда.

2022-10-16 17:54 UTC, otymko commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/MissingCommonModuleMethodDiagnostic.java
> +  private String getMethodNameByLocation(Range range) {
@artbear, а не надо это в Trees вынести?

2022-10-16 17:54 UTC, otymko commented on src/main/resources/com/github/_1c_syntax/bsl/languageserver/diagnostics/MissingCommonModuleMethodDiagnostic_ru.properties
> +privateMethod=Нельзя обращаться к закрытому, неэкспортному методу %s общего модуля %s
@artbear, побудительное сообщение, всегда лучше, чем информационное. Можно, например, написать:

`Исправьте обращение к закрытому, неэкспортному методу %s общего модуля %s`

2022-10-16 17:54 UTC, otymko commented on src/test/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/MissingCommonModuleMethodDiagnosticTest.java
> +      .hasMessageOnRange("Метод ЕщеОдинМетодНесуществующий общего модуля ПервыйОбщийМодуль не существует", 4, 22, 48) // TODO не находит https://github.com/1c-syntax/bsl-language-server/issues/2832
@artbear, что значит не находит? Этот ассерты должны сейчас работать или не должны?

2022-10-16 17:54 UTC, otymko commented
@artbear, я немного отписался в ревью, посмотри, пожалуйста.

2022-11-05 10:06 UTC, artbear commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/MissingCommonModuleMethodDiagnostic.java
> +  minutesToFix = 1,
@otymko Ставлю 5 минут

2022-11-05 10:06 UTC, artbear commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/MissingCommonModuleMethodDiagnostic.java
> +  private static class CallData {
исправил

2022-11-05 10:09 UTC, artbear commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/MissingCommonModuleMethodDiagnostic.java
> +  private String getMethodNameByLocation(Range range) {
@otymko все-таки не хочется переносить в Trees, т.к. 
1 код после Trees.findTerminalNodeContainsPosition слишком тривиален
2 и как назвать такой метод? у меня хорошее название не придумалось.

```java
  private String getMethodNameByLocation(Range range) {
    return Trees.findTerminalNodeContainsPosition(documentContext.getAst(), range.getEnd())
      .map(ParseTree::getText)
      .orElseThrow();
  }
```

2022-11-05 10:12 UTC, artbear commented on src/main/resources/com/github/_1c_syntax/bsl/languageserver/diagnostics/MissingCommonModuleMethodDiagnostic_ru.properties
> +privateMethod=Нельзя обращаться к закрытому, неэкспортному методу %s общего модуля %s
Согласен, переделал на `Исправьте обращение к закрытому, неэкспортному методу %s общего модуля %s`

2022-11-05 10:14 UTC, artbear commented on src/test/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/MissingCommonModuleMethodDiagnosticTest.java
> +      .hasMessageOnRange("Метод ЕщеОдинМетодНесуществующий общего модуля ПервыйОбщийМодуль не существует", 4, 22, 48) // TODO не находит https://github.com/1c-syntax/bsl-language-server/issues/2832
да, ненужные TODO остались, удаляю

2022-11-05 10:29 UTC, artbear commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/MissingCommonModuleMethodDiagnostic.java
> +  private String getMethodNameByLocation(Range range) {
Переделал по договоренности в статик-метод
```java
  private static String getMethodNameByLocation(BSLParserRuleContext node, Range range) {
    return Trees.findTerminalNodeContainsPosition(node, range.getEnd())
      .map(ParseTree::getText)
      .orElseThrow();
  }
```

2022-11-05 10:59 UTC, artbear commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/MissingCommonModuleMethodDiagnostic.java
> +      // TODO какие еще типы модулей поддержать? модули менеджеров - путаница с платформенными методами, без контекста не решить
пока решаю так
- сделал отдельный ишуз https://github.com/1c-syntax/bsl-language-server/issues/2926
- когда какие-то реализации с контекстом будут сделаны, можно доработать правило
  - буквально одно условие добавить и уточнить показ сообщений в замечание

а текущее правило будет только проверять только общие модули

2022-11-05 13:43 UTC, artbear commented
После исправлений проверил правило через Sarif на 3х конфигурациях - БСП, самописка на БСП, большая КА 2.5 с доработками

работает верно.

2022-11-08 03:11 UTC, otymko commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/MissingCommonModuleMethodDiagnostic.java
> +      // TODO какие еще типы модулей поддержать? модули менеджеров - путаница с платформенными методами, без контекста не решить
@artbear а номер задачи в TODO можешь еще написать?)

2022-11-08 03:12 UTC, otymko approved these changes

2022-11-08 03:13 UTC, otymko commented
@nixel2007, @asosnoviy у вас остались вопросы к ПР?

2022-12-12 19:48 UTC, theshadowco approved these changes

2022-12-12 19:48 UTC, theshadowco commented
@nixel2007 вливаем?

2022-12-21 06:35 UTC, merged