Client server params
1c-syntax/bsl-language-server pull request #2854
Opened 2022-07-19 05:30 UTC by artbear

## Описание

- реализация новой диагностики

## Связанные задачи

Closes #2853

## Чеклист

### Общие

- [ ] Ветка PR обновлена из develop
- [ ] Отладочные, закомментированные и прочие, не имеющие смысла участки кода удалены
- [ ] Изменения покрыты тестами
- [ ] Обязательные действия перед коммитом выполнены (запускал команду `gradlew precommit`)

### Для диагностик

- [ ] Описание диагностики заполнено для обоих языков (присутствуют файлы для обоих языков, для русского заполнено все подробно, перевод на английский можно опустить)

## Дополнительно

2022-09-25 10:52 UTC, artbear commented
@theshadowco @nixel2007 правило готово. примите его, если нет возражений.

2022-12-12 19:42 UTC, theshadowco commented
@artbear 
а чего столько тудушек осталось?

2022-12-23 07:30 UTC, otymko requested changes

2022-12-23 07:30 UTC, otymko commented on src/main/resources/com/github/_1c_syntax/bsl/languageserver/diagnostics/TransferringParametersBetweenClientAndServerDiagnostic_ru.properties
> +diagnosticMessage=Установите модификатор Знач для параметра %s метода %s
@artbear у `Знач` кавычки пропущены.

2022-12-23 07:30 UTC, otymko commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/TransferringParametersBetweenClientAndServerDiagnostic.java
> +  // TODO учесть подходящие типы модулей - только клиентские, только серверные или все?
@artbear, `todo`, либо решаем, либо создаем задачу и здесь оставляем ее номер..

2022-12-23 07:30 UTC, otymko commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/TransferringParametersBetweenClientAndServerDiagnostic.java
> +//    CompilerDirectiveKind.AT_CLIENT_AT_SERVER_NO_CONTEXT,
@artbear, закомментированный код.

2022-12-23 07:30 UTC, otymko commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/TransferringParametersBetweenClientAndServerDiagnostic.java
> +      .map(pair -> Triple.of(pair.getLeft(),
@artbear, не читабельно (

2022-12-23 07:30 UTC, otymko commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/TransferringParametersBetweenClientAndServerDiagnostic.java
> +      .map(triple ->  Triple.of(triple.getLeft(),
@artbear, не читабельно (

2022-12-23 07:30 UTC, otymko commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/TransferringParametersBetweenClientAndServerDiagnostic.java
> +      .forEach(triple -> triple.getMiddle().forEach(parameterDefinition ->
@artbear, не читабельно (

2022-12-23 07:30 UTC, otymko commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/TransferringParametersBetweenClientAndServerDiagnostic.java
> +      .map(pair -> Triple.of(pair.getLeft(),
предлагаю функциональщину на каждом этапе, если это несколько statement вынести в методы с говорящими именами. Будет более читабельно и сразу можно будет понять, что происходит.

2022-12-23 07:30 UTC, otymko commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/TransferringParametersBetweenClientAndServerDiagnostic.java
> +      ); // TODO добавить места вызовов как связанную информацию
@artbear, todo

2022-12-23 07:30 UTC, otymko commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/TransferringParametersBetweenClientAndServerDiagnostic.java
> +      .filter(variable -> parameterDefinition.getRange().getStart().equals(variable.getSelectionRange().getStart()))
@artbear, а у Range там никаких методов для этого нет?

2022-12-23 07:30 UTC, otymko commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/TransferringParametersBetweenClientAndServerDiagnostic.java
> +  private List<ParameterDefinition> notAssignedParams(MethodSymbol method, List<ParameterDefinition> parameterDefinitions) {
@artbear, имя методы режет взор. Мб здесь "getNotAssignedParams" или "calcNotAssignedParams"? А ниже у метода - + приставка "Is"?

2022-12-23 07:30 UTC, otymko commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/TransferringParametersBetweenClientAndServerDiagnostic.java
> +    // TODO учесть возможность вызова из клиентского модуля, в котором не нужны\не указаны директивы компиляции
@artbear, todo

2022-12-23 07:30 UTC, otymko commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/TransferringParametersBetweenClientAndServerDiagnostic.java
> +      .map(methodSymbol -> Pair.of(methodSymbol,
@artbear, не читабельно ( мб в отдельный метод?

2022-12-23 07:30 UTC, otymko commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/TransferringParametersBetweenClientAndServerDiagnostic.java
> +        notAssignedParams(triple.getLeft(), triple.getMiddle()),
@artbear, кажется имеется в виде не измененные "not changed", а не присвоенные?

2022-12-23 07:30 UTC, otymko commented on src/test/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/TransferringParametersBetweenClientAndServerDiagnosticTest.java
> +    return String.format("Установите модификатор Знач для параметра %s метода %s",
@artbear, кстати, а мы это из ресурсов получить не можем?

2022-12-23 07:30 UTC, otymko commented on src/test/resources/diagnostics/TransferringParametersBetweenClientAndServerDiagnostic.bsl
> +    ЕщеМетод(Парам1);
@artbear, а где реализация метода ЕщеМетод?

2022-12-23 07:30 UTC, otymko commented on src/test/resources/diagnostics/TransferringParametersBetweenClientAndServerDiagnostic.bsl
> +    Метод(Парам1);
@artbear, а где реализация метода "Метод"?

2022-12-23 07:30 UTC, otymko commented on src/test/resources/diagnostics/TransferringParametersBetweenClientAndServerDiagnostic.bsl
> +&НаКлиенте
@artbear, хорошо. А если будет такая ситуация. Вот у нас есть структура на клиенте, я передаю ее в метод на сервере, в методе на сервере я изменяю структуру - по имени свойства переназначаю его значение. Что с этом случае будет?

Либо я вообще не понял, зачем эта диагностика нужна.

2022-12-23 07:31 UTC, otymko commented
@artbear, просьба, поправь, пожалуйста, оформление стримов, не читабельны через ПР(

2022-12-24 09:30 UTC, artbear commented on src/test/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/TransferringParametersBetweenClientAndServerDiagnosticTest.java
> +    return String.format("Установите модификатор Знач для параметра %s метода %s",
> @artbear, кстати, а мы это из ресурсов получить не можем?

я специально явно укаываю строку-копию, чтобы не пропустить пустые ресурсы.
Предлагаю так и оставить.

2022-12-24 09:30 UTC, artbear commented on src/main/resources/com/github/_1c_syntax/bsl/languageserver/diagnostics/TransferringParametersBetweenClientAndServerDiagnostic_ru.properties
> +diagnosticMessage=Установите модификатор Знач для параметра %s метода %s
Исправил

2022-12-24 09:54 UTC, artbear commented on src/test/resources/diagnostics/TransferringParametersBetweenClientAndServerDiagnostic.bsl
> +&НаКлиенте
> @artbear, хорошо. А если будет такая ситуация. Вот у нас есть структура на клиенте, я передаю ее в метод на сервере, в методе на сервере я изменяю структуру - по имени свойства переназначаю его значение. Что с этом случае будет?
> 
> Либо я вообще не понял, зачем эта диагностика нужна.

@otymko добавил пример с пояснением в документацию

2022-12-24 09:55 UTC, artbear commented on src/test/resources/diagnostics/TransferringParametersBetweenClientAndServerDiagnostic.bsl
> +    Метод(Парам1);
добавил Метод()

2022-12-24 09:56 UTC, artbear commented on src/test/resources/diagnostics/TransferringParametersBetweenClientAndServerDiagnostic.bsl
> +    ЕщеМетод(Парам1);
добавил ЕщеМетод

2022-12-24 09:59 UTC, artbear commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/TransferringParametersBetweenClientAndServerDiagnostic.java
> +      .filter(variable -> parameterDefinition.getRange().getStart().equals(variable.getSelectionRange().getStart()))
> @artbear, а у Range там никаких методов для этого нет?

явно похожего нет.
у Range есть полное сравнение equal, а я для скорости проверяю только начало, т.к. других совпадений параметров по позиции в одном модуле быть не может

2022-12-24 10:03 UTC, artbear commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/TransferringParametersBetweenClientAndServerDiagnostic.java
> +  private List<ParameterDefinition> notAssignedParams(MethodSymbol method, List<ParameterDefinition> parameterDefinitions) {
да, переименовал оба метода, у последнего инвертировал логику
```java
  private List<ParameterDefinition> calcNotAssignedParams(MethodSymbol method, List<ParameterDefinition> parameterDefinitions) {
    return parameterDefinitions.stream()
      .filter(parameterDefinition -> isAssignedParam(method, parameterDefinition))
      .collect(Collectors.toUnmodifiableList());
  }

  private boolean isAssignedParam(MethodSymbol method, ParameterDefinition parameterDefinition) {
    return getVariableByParameter(method, parameterDefinition)
      .noneMatch(variableSymbol -> referenceIndex.getReferencesTo(variableSymbol).stream()
        .anyMatch(ref -> ref.getOccurrenceType() == OccurrenceType.DEFINITION));
  }
```

2022-12-24 11:26 UTC, artbear commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/TransferringParametersBetweenClientAndServerDiagnostic.java
> +//    CompilerDirectiveKind.AT_CLIENT_AT_SERVER_NO_CONTEXT,
исправил

2022-12-24 11:26 UTC, artbear commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/TransferringParametersBetweenClientAndServerDiagnostic.java
> +      .map(pair -> Triple.of(pair.getLeft(),
да, переделал\упростил

2022-12-24 11:27 UTC, artbear commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/TransferringParametersBetweenClientAndServerDiagnostic.java
> +      .forEach(triple -> triple.getMiddle().forEach(parameterDefinition ->
переделал\упростил

2022-12-24 11:27 UTC, artbear commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/TransferringParametersBetweenClientAndServerDiagnostic.java
> +      .map(methodSymbol -> Pair.of(methodSymbol,
переделал\упростил

2022-12-24 11:50 UTC, artbear commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/TransferringParametersBetweenClientAndServerDiagnostic.java
> +    // TODO учесть возможность вызова из клиентского модуля, в котором не нужны\не указаны директивы компиляции
перенес TODO в задачу https://github.com/1c-syntax/bsl-language-server/issues/2972

2022-12-24 11:50 UTC, artbear commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/TransferringParametersBetweenClientAndServerDiagnostic.java
> +      ); // TODO добавить места вызовов как связанную информацию
перенес TODO в задачу https://github.com/1c-syntax/bsl-language-server/issues/2972

2022-12-24 11:51 UTC, artbear commented
> @artbear а чего столько тудушек осталось?

@theshadowco @otymko 
перенес все TODO в задачу https://github.com/1c-syntax/bsl-language-server/issues/2972

2022-12-24 11:53 UTC, artbear commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/TransferringParametersBetweenClientAndServerDiagnostic.java
> +        notAssignedParams(triple.getLeft(), triple.getMiddle()),
я учитываю\пропускаю именно "не присвоенные" параметры

2022-12-24 11:54 UTC, artbear commented
@otymko почти все замечания исправлены. в паре мест, где я не совсем согласен, я оставил свой комментарий.

2023-03-26 12:27 UTC, artbear commented
@theshadowco @otymko @nixel2007 Правило готово, все замечания исправлены.

Правило работает в Инфостарте уже много месяцев!!

Досмотрите уже ПР и принимайте его, пожалуйста!

2023-03-29 13:35 UTC, theshadowco approved these changes

2023-03-31 08:22 UTC, merged