Правило "Обработчик регламентного задания"
1c-syntax/bsl-language-server pull request #2862
Opened 2022-07-24 09:47 UTC by artbear

## Описание

- реализовал правило

## Связанные задачи

Closes #2861

## Чеклист

### Общие

- [x] Ветка PR обновлена из develop
- [x] Отладочные, закомментированные и прочие, не имеющие смысла участки кода удалены
- [x] Изменения покрыты тестами
- [x] Обязательные действия перед коммитом выполнены (запускал команду `gradlew precommit`)

### Для диагностик

- [ ] Описание диагностики заполнено для обоих языков (присутствуют файлы для обоих языков, для русского заполнено все подробно, перевод на английский можно опустить)

## Дополнительно

2022-07-24 10:02 UTC, artbear commented
@nixel2007 все тесты прошли, только шаг Sentry упал. ИМХО не по моей вине )

>Error: Environment variable SENTRY_ORG is missing an organization slug

https://github.com/artbear/bsl-language-server/runs/7487025826?check_suite_focus=true

2022-07-24 10:14 UTC, nixel2007 commented
Да, там надо gatekeeper подключить

2022-07-24 11:01 UTC, artbear commented
- исправил ошибку в AbstractMetadataDiagnostic - в метод checkMetadata в некоторых случаях попадали метаданные, не заданные фильтром
  - обнаружил при запуске анализа правила на БСП 3.1 через ком.строку

2022-07-24 11:25 UTC, artbear commented
Правило готово.

Проверено на БСП 3.1 и КА 2.4

В КА найдены правильные срабатывания на пустые методы регл.заданий и даже на дубль обработчика в двух регл.заданиях

![image](https://user-images.githubusercontent.com/2920817/180644769-6e9bd2aa-701e-4caa-bf89-6059cf81767c.png)

2022-07-24 11:33 UTC, artbear commented
Как и предполагалось, есть ложные срабатывания на непредопределенные регл.задания с параметрами, о чем и написано в документации.

2022-07-25 03:58 UTC, theshadowco approved these changes

2022-07-25 04:09 UTC, nixel2007 commented
Я бы подождал/сделал доработки в  mdclasses

2022-07-25 05:18 UTC, artbear commented
> Я бы подождал/сделал доработки в mdclasses. Фпшить на ровном месте не хочется.

зачем затягивать с полезным правилом?

давай его смержим, а уже дальше доработаем.

в крайнем случае, могу сделать настройку для включения\отключения проверки на параметры, чтобы не было ложных ФП.

2022-07-25 05:51 UTC, nixel2007 commented
Добавить одно поле в mdclasses - это не затягивать.

2022-07-25 17:13 UTC, artbear commented
> Добавить одно поле в mdclasses - это не затягивать.

кто и когда его добавит? )

2022-07-25 17:18 UTC, artbear commented
> > Добавить одно поле в mdclasses - это не затягивать.
> 
> кто и когда его добавит? )

ну и самое главное - когда выйдет релиз с поддержкой этой фичи уже после вливания МР с доработкой?

@theshadowco сможешь оперативно выпустить релиз , если  я сделаю доработку?

2022-07-25 18:06 UTC, artbear commented
@nixel2007 @theshadowco я реализовал поддержку необходимых атрибутов регл.заданий

смотрите ПР https://github.com/1c-syntax/mdclasses/pull/364

2022-07-28 03:30 UTC, theshadowco commented
@artbear https://github.com/1c-syntax/mdclasses/releases/tag/v0.10.1

2022-07-28 03:44 UTC, theshadowco commented
@artbear 
Точнее https://github.com/1c-syntax/mdclasses/releases/tag/v0.10.2 ибо прошлая реализация была с ошибкой и я ХЗ как тебе это удалось

2022-09-25 10:29 UTC, artbear commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/ScheduledJobHandlerDiagnostic.java
> +      .map((List<MDScheduledJob> mdScheduledJobs) -> {
Сонар считает, что peek опасен. я осознанно оставил здесь текущий код.

2022-09-25 10:52 UTC, artbear commented
@theshadowco @nixel2007 правило готово. примите его, если нет возражений.

подключил релиз mdclasses 0.10.2
тесты прошли

2022-10-16 18:15 UTC, otymko requested changes

2022-10-16 18:15 UTC, otymko commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/ScheduledJobHandlerDiagnostic.java
> +  private void fireIssueForDoubles(List<MDScheduledJob> mdScheduledJobs) {
@artbear, а зачем здесь список MDScheduledJob? Может выше в стриме сделать получение одного?

2022-10-16 18:15 UTC, otymko commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/ScheduledJobHandlerDiagnostic.java
> +    final var commonModuleOptional = documentContext.getServerContext().getConfiguration().getCommonModule(moduleName);
@artbear, длинно.. (

2022-10-16 18:15 UTC, otymko commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/ScheduledJobHandlerDiagnostic.java
> +  public static final String DIAGNOSTIC_MESSAGE = "diagnosticMessage";
@artbear, может я что-то пропустил, а почему они публичные, эти константы имен ресурсных строк? В тесте вроде их использование не увидел.

2022-10-16 18:15 UTC, otymko commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/ScheduledJobHandlerDiagnostic.java
> +  private static String getFullName(MDCommonModule mdCommonModule, String methodName) {
@artbear, статические методы хорошо смотрятся до конструкторов и методов инстанса

2022-10-16 18:15 UTC, otymko commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/ScheduledJobHandlerDiagnostic.java
> +  private boolean isEmptyMethodBody(MethodSymbol methodSymbol) {
@artbear, порядок как-то нарушен. Сначала идет методы инстанса, потом статик методы класса, потом опять методы инстанса..

2022-10-16 18:15 UTC, otymko commented on src/test/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/ScheduledJobHandlerDiagnosticTest.java
> +  private List<Diagnostic> checkMockHandler(String methodPath) {
@artbear, разрывается описание тестовых методов внутренним методом..

2022-10-16 18:15 UTC, otymko commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/ScheduledJobHandlerDiagnostic.java
> +  severity = DiagnosticSeverity.BLOCKER,
@artbear, а точно блокер? Инфобаза на конфигурации с такой проблемой обновится и запустится?

2022-10-31 18:14 UTC, artbear commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/ScheduledJobHandlerDiagnostic.java
> +    final var commonModuleOptional = documentContext.getServerContext().getConfiguration().getCommonModule(moduleName);
@otymko а чем\как предлагаешь заменить?
вынести в отдельную переменную конфигурацию? 
думаешь, так лучше?

2022-10-31 18:14 UTC, artbear commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/ScheduledJobHandlerDiagnostic.java
> +  public static final String DIAGNOSTIC_MESSAGE = "diagnosticMessage";
проглядел, исправлю

2022-10-31 18:29 UTC, artbear commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/ScheduledJobHandlerDiagnostic.java
> +  private void fireIssueForDoubles(List<MDScheduledJob> mdScheduledJobs) {
@otymko так в этом методе и нужен список дублей по обработчику.
или я не понимаю твоего вопроса.

2022-10-31 18:34 UTC, artbear commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/ScheduledJobHandlerDiagnostic.java
> +  private static String getFullName(MDCommonModule mdCommonModule, String methodName) {
исправлено.

2022-10-31 18:34 UTC, artbear commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/ScheduledJobHandlerDiagnostic.java
> +  private boolean isEmptyMethodBody(MethodSymbol methodSymbol) {
исправлено.

2022-10-31 18:34 UTC, artbear commented on src/test/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/ScheduledJobHandlerDiagnosticTest.java
> +  private List<Diagnostic> checkMockHandler(String methodPath) {
исправлено.

2022-10-31 18:41 UTC, artbear commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/AbstractMetadataDiagnostic.java
>        if (mdo instanceof AbstractMDObjectBSL) {
исправлено.

2022-11-01 04:52 UTC, otymko commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/ScheduledJobHandlerDiagnostic.java
> +  private void fireIssueForDoubles(List<MDScheduledJob> mdScheduledJobs) {
Я уже забыл мысль, которую тут держал. Давай оставим как есть.

2022-11-01 04:53 UTC, otymko commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/ScheduledJobHandlerDiagnostic.java
> +    final var commonModuleOptional = documentContext.getServerContext().getConfiguration().getCommonModule(moduleName);
@artbear, либо перевод строки =) В экран не вмещается, намек на это.

2022-11-01 04:54 UTC, otymko approved these changes

2022-11-01 06:41 UTC, otymko commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/ScheduledJobHandlerDiagnostic.java
> +    final var commonModuleOptional = documentContext.getServerContext().getConfiguration().getCommonModule(moduleName);
@artbear, поправишь и я залью

2022-11-03 14:25 UTC, artbear commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/ScheduledJobHandlerDiagnostic.java
> +    final var commonModuleOptional = documentContext.getServerContext().getConfiguration().getCommonModule(moduleName);
> @artbear, поправишь и я залью

@otymko перенес длинное выражение после = на другую строку с отступом.
так устроит?

если да, замержишь?

2022-11-03 14:31 UTC, merged

2022-11-03 14:33 UTC, artbear commented
Наконец-то мерж! Большое спасибо @otymko !