Новая диагностика "Не указан обязательный параметр метода"
1c-syntax/bsl-language-server pull request #2922
Opened 2022-10-28 11:43 UTC by alkoleft

## Описание

Добавлена диагностика по #1010 и #489 

## Связанные задачи

Closes #1010, #489 

## Чеклист

### Общие

- [ ] Ветка PR обновлена из develop
- [ ] Отладочные, закомментированные и прочие, не имеющие смысла участки кода удалены
- [ ] Изменения покрыты тестами
- [ ] Обязательные действия перед коммитом выполнены (запускал команду `gradlew precommit`)

### Для диагностик

- [ ] Описание диагностики заполнено для обоих языков (присутствуют файлы для обоих языков, для русского заполнено все подробно, перевод на английский можно опустить)

## Дополнительно

2022-10-28 18:17 UTC, nixel2007 commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/MissedRequiredParameterDiagnostic.java
> +  Map<Range, MethodCall> calls = new HashMap<>();
```suggestion
  private final Map<Range, MethodCall> calls = new HashMap<>();
```

2022-10-28 18:19 UTC, nixel2007 commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/MissedRequiredParameterDiagnostic.java
> +    for (var reference : referenceIndex.getReferencesFrom(documentContext.getUri(), SymbolKind.Method)) {
а действительно нужен И refrenceIndex И visitGloblaMethodCall/visitMethodCall? что такого ловят обращения к дереву, что не ловит реф-индекс?

2022-10-28 18:20 UTC, nixel2007 commented on src/test/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/MissedRequiredParameterDiagnosticTest.java
> +    initServerContext(Absolute.path(PATH_TO_METADATA));
нужна аннотация @CleanupContextBeforeClassAndAfterEachTestMethod на класс

2022-10-28 20:34 UTC, alkoleft commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/MissedRequiredParameterDiagnostic.java
> +    for (var reference : referenceIndex.getReferencesFrom(documentContext.getUri(), SymbolKind.Method)) {
1. referenceIndex не содержит параметров вызова.
2. использую referenceIndex с прицелом на будущее, когда он подружится с dfa, там будет больше инфы, например обращение к методам объекта.
3. + не хотел копипастить методы которые имеются в referenceIndex. Если я верно его понимаю, оверхеда его использование дает не много.

2022-10-30 10:13 UTC, artbear commented
Из описания непонятно, реализована проверка только локальных методов или методы общих модулей, менеджеров объектов также проверяются.

предлагаю уточнить шапку ПР

2022-10-30 10:15 UTC, artbear commented on docs/diagnostics/MissedRequiredParameter.md
> +При вызове функций не следует пропускать обязательные параметры. В противном случае, в параметр будет передано значение `Неопределено`, на которое функция может быть не рассчитана. Если же значение `
```suggestion
При вызове функций не следует пропускать обязательные параметры. В противном случае в параметр будет передано значение `Неопределено`, на которое функция может быть не рассчитана. 
Если же значение `Неопределено` является допустимым, то нужно 
- или его передавать в функцию явно
- или сделать этот параметр необязательным со значением по умолчанию `Неопределено`.
```

Предлагаю так уточнить.

2022-10-30 10:52 UTC, artbear requested changes
Есть замечания

2022-10-30 10:52 UTC, artbear commented on docs/diagnostics/MissedRequiredParameter.md
> +https://its.1c.ru/db/v8std#content:640:hdoc
нужно расшифровать ссылку аналогично рекомендациям в шаблоне ишью

2022-10-30 10:52 UTC, artbear commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/MissedRequiredParameterDiagnostic.java
> +  severity = DiagnosticSeverity.INFO,
Почему такой низкий уровень? в основном ишью #489 указан уровень Major

2022-10-30 10:52 UTC, artbear commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/MissedRequiredParameterDiagnostic.java
> +  type = DiagnosticType.CODE_SMELL,
Почему не ошибка, как в основном ишью https://github.com/1c-syntax/bsl-language-server/issues/489

2022-10-30 10:52 UTC, artbear commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/MissedRequiredParameterDiagnostic.java
> +    for (var reference : referenceIndex.getReferencesFrom(documentContext.getUri(), SymbolKind.Method)) {
Соглашусь с Никитой, что двойной вызов необязателен.

в моем давно висящем ПР прекрасно достаются данные о методе
- пример https://github.com/1c-syntax/bsl-language-server/pull/2854/files#diff-928a6414ee9149176ea50aee0c9411fd827940709a6c5226ae14d57724d88c7aR103

2022-10-30 10:52 UTC, artbear commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/MissedRequiredParameterDiagnostic.java
> +    ParameterDefinition methodParameter;
зачем эта переменная вынесена за цикл?
- она же используется только внутри цикла

2022-10-30 10:52 UTC, artbear commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/MissedRequiredParameterDiagnostic.java
> +        checkMethod((MethodSymbol) reference.getSymbol(), calls.get(reference.getSelectionRange()));
Вижу ненужный повторный поиск по ключу в коллекцию calls

быстрее сразу получить результат по ключу и проверить его наличие

2022-10-30 10:52 UTC, artbear commented on src/main/resources/com/github/_1c_syntax/bsl/languageserver/diagnostics/MissedRequiredParameterDiagnostic_en.properties
> +diagnosticName=Missed required parameter
Английское название диагностики отличается от русского названия. В русском есть "параметр метода", чего нет в английском.

2022-10-30 10:52 UTC, artbear commented on src/test/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/MissedRequiredParameterDiagnosticTest.java
> +    assertThat(diagnostics).hasSize(5);
указано 5 срабатываний, а ниже проверяется только 4

2022-10-30 10:52 UTC, artbear commented on src/test/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/MissedRequiredParameterDiagnosticTest.java
> +    assertThat(diagnostics).hasSize(11);
указано 11 срабатываний, а ниже проверяется только 8

2022-10-30 10:52 UTC, artbear commented on src/test/resources/diagnostics/MissedRequiredParameterDiagnostic.bsl
> +    Результат = Сложение(, 2);
а почему нет кейса на висящую запятую? `Сложение(1, );`

2022-10-31 15:17 UTC, theshadowco commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/MissedRequiredParameterDiagnostic.java
> +  void appendMethodCall(Token methodName, BSLParser.DoCallContext doCallContext, BSLParserRuleContext node) {
private

2022-10-31 15:45 UTC, otymko requested changes

2022-10-31 15:45 UTC, otymko commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/MissedRequiredParameterDiagnostic.java
> +  severity = DiagnosticSeverity.INFO,
@alkoleft, важность не соответствует тем, что указаны в двух ишузах.

2022-10-31 18:18 UTC, asosnoviy commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/MissedRequiredParameterDiagnostic.java
> +    calls.clear();
@otymko А очистка пустого как то критична?

2022-10-31 18:26 UTC, alkoleft commented on src/test/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/MissedRequiredParameterDiagnosticTest.java
> +  private static final String PATH_TO_METADATA = "src/test/resources/metadata/designer";
Так получилось. буду аккуратнее

2022-10-31 18:31 UTC, alkoleft commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/MissedRequiredParameterDiagnostic.java
> +    for (var reference : referenceIndex.getReferencesFrom(documentContext.getUri(), SymbolKind.Method)) {
@nixel2007 Чего молчишь, можно конечно индекс доработать (добавить параметры), но надо ли.

2022-11-01 04:25 UTC, otymko commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/MissedRequiredParameterDiagnostic.java
> +    calls.clear();
@asosnoviy, думаю, что нет. Но может вводить в заблуждение.

2022-11-01 04:26 UTC, otymko commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/MissedRequiredParameterDiagnostic.java
> +  public ParseTree visitMethodCall(BSLParser.MethodCallContext ctx) {
тестом бы покрыть тогда

2022-11-01 10:35 UTC, theshadowco approved these changes

2022-11-01 10:40 UTC, theshadowco commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/MissedRequiredParameterDiagnostic.java
> +    String methodName = ctx.methodName().IDENTIFIER().getText();
@alkoleft привыкай использовать var

2022-11-01 10:40 UTC, theshadowco commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/MissedRequiredParameterDiagnostic.java
> +    MethodCall methodCall = new MethodCall();
var

2022-11-01 10:40 UTC, theshadowco commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/MissedRequiredParameterDiagnostic.java
> +    for (int i = 0; i < methodCall.parameters.length; i++) {
var в цикле

2022-11-01 10:40 UTC, theshadowco commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/MissedRequiredParameterDiagnostic.java
> +    int callParametersCount = callInfo.parameters.length;
var

2022-11-01 10:40 UTC, theshadowco commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/MissedRequiredParameterDiagnostic.java
> +    for (int i = 0; i < methodDefinition.getParameters().size(); i++) {
var

2022-11-01 13:19 UTC, alkoleft commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/MissedRequiredParameterDiagnostic.java
> +  public ParseTree visitMethodCall(BSLParser.MethodCallContext ctx) {
Реализовал

2022-11-01 13:25 UTC, otymko approved these changes

2022-11-01 17:20 UTC, theshadowco commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/MissedRequiredParameterDiagnostic.java
> +        diagnosticStorage.addDiagnostic(callInfo.range, info.getMessage(methodParameter.getName()));
Лучше не вешать несколько диагностик на один рендж, а одну с перечислением пропущенных параметров. Либо повесить одну диагностику и добавить связанные ренджи с именами параметров

2022-11-01 21:58 UTC, alkoleft commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/MissedRequiredParameterDiagnostic.java
> +        diagnosticStorage.addDiagnostic(callInfo.range, info.getMessage(methodParameter.getName()));
Сделал

2022-11-01 21:59 UTC, alkoleft commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/references/ReferenceIndexFiller.java
> +    private final Set<String> THIS_OBJECT_IDENTIFIER = new TreeSet<>(String.CASE_INSENSITIVE_ORDER) {{
Таки норм, вроде

2022-11-01 22:00 UTC, alkoleft commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/MissedRequiredParameterDiagnostic.java
> +    for (int i = 0; i < methodDefinition.getParameters().size(); i++) {
Думаю тут излишне или var повсеместно кроме объявлений?

2022-11-02 01:50 UTC, sfaqer commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/references/ReferenceIndexFiller.java
> +    private final Set<String> THIS_OBJECT_IDENTIFIER = new TreeSet<>(String.CASE_INSENSITIVE_ORDER) {{
Дело не в форматировании, тут https://www.baeldung.com/java-double-brace-initialization который в целом антипаттерн, тут анонимный наследник триСета создаётся через этот инициализатор

2022-11-02 08:29 UTC, alkoleft commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/references/ReferenceIndexFiller.java
> +    private final Set<String> THIS_OBJECT_IDENTIFIER = new TreeSet<>(String.CASE_INSENSITIVE_ORDER) {{
Почитал про double brace еще до коммита, насколько я понял не вызывает проблем для моего случая со статическим финальным полем. Но исправлю.

2022-11-02 19:14 UTC, theshadowco commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/MissedRequiredParameterDiagnostic.java
> +      var message = info.getMessage('\'' + String.join("', '", missedParameters) + '\'');
string.format ?

2022-11-07 18:39 UTC, alkoleft commented
Отменил изменения ReferenceIndex

2022-12-12 19:36 UTC, theshadowco approved these changes

2022-12-12 19:36 UTC, theshadowco commented
@nixel2007 
Вливаем?

2022-12-21 15:13 UTC, merged