Использование СистемнаяИнформация
1c-syntax/bsl-language-server pull request #2931
Opened 2022-11-09 22:24 UTC by alkoleft

## Описание
Реализовано правило для диагностики "Использование СистемнаяИнформация"

> Объект СистемнаяИнформация предоставляет данные о о компьютере и конфигурации в 1С, которая может быть использована в злонамерянных целях.
> 
> Необходимо подсвечивать места использования.

## Связанные задачи

Closes #577

## Чеклист

### Общие

- [ ] Ветка PR обновлена из develop
- [ ] Отладочные, закомментированные и прочие, не имеющие смысла участки кода удалены
- [ ] Изменения покрыты тестами
- [ ] Обязательные действия перед коммитом выполнены (запускал команду `gradlew precommit`)

### Для диагностик

- [ ] Описание диагностики заполнено для обоих языков (присутствуют файлы для обоих языков, для русского заполнено все подробно, перевод на английский можно опустить)

## Дополнительно

2022-11-10 06:34 UTC, asosnoviy commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/color/ConstructorColorInformationSupplier.java
> +      .filter(newExpression -> Constructors.typeName(newExpression).filter(name -> COLOR_PATTERN.matcher(name).matches()).isPresent())
А вот эти изменения от диагностики или случайно залетели?

2022-11-10 10:49 UTC, otymko requested changes

2022-11-10 10:49 UTC, otymko commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/utils/Constructors.java
> +public class Constructors {
@alkoleft, jdoc поможет потом понять, зачем добавили этот класс )

2022-11-10 10:49 UTC, otymko commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/utils/Constructors.java
> +  public static Optional<String> typeName(BSLParser.NewExpressionContext newExpression) {
@alkoleft, jdoc бы на публичные методы..

2022-11-10 10:49 UTC, otymko commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/utils/Constructors.java
> +  static private <T> Optional<T> first(List<T> list) {
@alkoleft, приватный?

2022-11-10 10:49 UTC, otymko commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/utils/Constructors.java
> +      .or(() -> Optional.ofNullable(newExpression.doCall())
@alkoleft, если or содержимое вынести в отдельный метод - будет читабельнее немного.

2022-11-10 10:49 UTC, otymko commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/utils/Constructors.java
> +        .map(constValueText -> constValueText.substring(1, constValueText.length() - 1)));
@alkoleft, а у нас в проекте не завалялся метод очистки строки от кавычек? Где-то я видел..

2022-11-10 10:49 UTC, otymko commented on src/main/resources/com/github/_1c_syntax/bsl/languageserver/diagnostics/UseSystemInformationDiagnostic_ru.properties
> +diagnosticMessage=Необходимо избавиться от использования объекта `СистемнаяИнформация`
@alkoleft, может просто - "Избавьтесь от .."?

2022-11-10 10:49 UTC, otymko commented on src/test/resources/diagnostics/UseSystemInformationDiagnostic.bsl
> +СистемнаяИнформация = Новый("СистемнаяИнформация2");
@alkoleft, давай докинем еще вариант:
```bsl
ИмяТипа = "СистемнаяИнформация";
СистемнаяИнформация = Новый(ИмяТипа);
```

2022-11-10 10:49 UTC, otymko commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/color/ConstructorColorInformationSupplier.java
> +      .filter(newExpression -> Constructors.typeName(newExpression).filter(name -> COLOR_PATTERN.matcher(name).matches()).isPresent())
@asosnoviy это проверка работы нового класса.

2022-11-10 15:38 UTC, alkoleft commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/color/ConstructorColorInformationSupplier.java
> +      .filter(newExpression -> Constructors.typeName(newExpression).filter(name -> COLOR_PATTERN.matcher(name).matches()).isPresent())
Вынес метод для получение имени типа из конструктора (Новый БлаБла) в отдельный класс, так как нашел копипасту и заменил ее, на этот метод.

Все тесты успешны)

2022-11-10 15:40 UTC, alkoleft commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/utils/Constructors.java
> +  static private <T> Optional<T> first(List<T> list) {
Ну да, чисто для обслуживания метода выше.

2022-11-10 15:40 UTC, alkoleft commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/utils/Constructors.java
> +      .or(() -> Optional.ofNullable(newExpression.doCall())
Использовал код из другого метода с небольшими доработками, ок поправлю

2022-11-10 15:41 UTC, alkoleft commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/utils/Constructors.java
> +        .map(constValueText -> constValueText.substring(1, constValueText.length() - 1)));
Я видел на основе регулярки, но этот шустрее, поищу, может найду.

2022-11-10 15:41 UTC, alkoleft commented on src/main/resources/com/github/_1c_syntax/bsl/languageserver/diagnostics/UseSystemInformationDiagnostic_ru.properties
> +diagnosticMessage=Необходимо избавиться от использования объекта `СистемнаяИнформация`
Ок

2022-11-10 15:44 UTC, alkoleft commented on src/test/resources/diagnostics/UseSystemInformationDiagnostic.bsl
> +СистемнаяИнформация = Новый("СистемнаяИнформация2");
А зачем? Может туду в диагностике, что она ждет локального dfa

2022-11-10 15:52 UTC, alkoleft commented
Есть один момент, который хотелось бы реализовать - в тикете есть замечание о том, что не стоит проверять клиент.
Поэтому думал создать параметр для исключения клиента, но встал вопрос. Если ли методы для вычисления директив препроцессора 
```bsl
#Если ТонкийКлиет ИЛИ Сервер Тогда
#КонецЕсли
```
А также есть ли метод, который возвращает доступные контексты исполнения модуля и возможно можно ли ориентироваться только на основной режим запуска конфигурации при этом

2022-11-10 17:34 UTC, otymko commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/utils/Constructors.java
> +  static private <T> Optional<T> first(List<T> list) {
Статик привейт или привейт Статик?

2022-11-10 17:34 UTC, otymko commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/utils/Constructors.java
> +        .map(constValueText -> constValueText.substring(1, constValueText.length() - 1)));
Я к тому, чтобы один метод дёргать

2022-11-10 19:10 UTC, theshadowco commented
> А также есть ли метод, который возвращает доступные контексты исполнения модуля и возможно можно ли ориентироваться только на основной режим запуска конфигурации при этом

С препроцессором пока все плохо. Можно ориентироваться на тип модуля (прописать в аннотации к классу), а для общих модулей на наличие флагов у них: если только клиентские флаги - пропустить

2022-11-10 19:18 UTC, alkoleft commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/utils/Constructors.java
> +public class Constructors {
Добавил

2022-11-10 19:18 UTC, alkoleft commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/utils/Constructors.java
> +  public static Optional<String> typeName(BSLParser.NewExpressionContext newExpression) {
Добавил

2022-11-10 19:18 UTC, alkoleft commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/utils/Constructors.java
> +  static private <T> Optional<T> first(List<T> list) {
готово

2022-11-11 03:05 UTC, otymko commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/utils/Constructors.java
> +public class Constructors {
@alkoleft, теперь понятно. Название не соответствует тому, что именно делает класс. Давай в имени класса уточним, какие именно конструкторы. Либо хотя бы пакет другой с говорящим именем придумаем. Например, я бы мог назвать класс "BslConstructors", в пакете "**.language"

2022-11-11 03:06 UTC, otymko commented on src/main/resources/com/github/_1c_syntax/bsl/languageserver/diagnostics/UseSystemInformationDiagnostic_ru.properties
> +diagnosticMessage=Избавьтеся от использования объекта `СистемнаяИнформация`
@alkoleft, опечатка в "Избавьтеся"

2022-11-11 10:32 UTC, alkoleft commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/utils/Constructors.java
> +public class Constructors {
перенес в пакет `package com.github._1c_syntax.bsl.languageserver.utils.bsl`.

Туда бы остальные схожие классы бы перекинуть...
А название оставил прежним, тк есть опять же схожие классы со старой схемой наименования `Methods`, `Modules`

2022-12-09 10:31 UTC, alkoleft commented on src/test/resources/diagnostics/UseSystemInformationDiagnostic.bsl
> +СистемнаяИнформация = Новый("СистемнаяИнформация2");
Добавлено

2022-12-09 10:32 UTC, alkoleft commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/utils/Constructors.java
> +        .map(constValueText -> constValueText.substring(1, constValueText.length() - 1)));
Исправлено

2022-12-12 19:34 UTC, theshadowco commented
@otymko @nixel2007 
Вливаем?

2022-12-21 15:14 UTC, merged