Правило Не установлен флаг "Запрет незаполненных значений" для измерений регистра
1c-syntax/bsl-language-server pull request #2976
Opened 2023-01-16 20:25 UTC by artbear

## Описание

- Реализация #2975
- Исправлена ошибка AbstractMetadataDiagnostic - неверно обрабатывались метаданные с несколькими модулями
  - небольшое ускорение проверки модулей в этом классе
- класс-утилита MdoReferences с полезными методами

## Связанные задачи

Closes #2975

## Чеклист

### Общие

- [x] Ветка PR обновлена из develop
- [x] Отладочные, закомментированные и прочие, не имеющие смысла участки кода удалены
- [x] Изменения покрыты тестами
- [x] Обязательные действия перед коммитом выполнены (запускал команду `gradlew precommit`)

### Для диагностик

- [x] Описание диагностики заполнено для обоих языков (присутствуют файлы для обоих языков, для русского заполнено все подробно, перевод на английский можно опустить)

## Дополнительно

2023-01-16 21:02 UTC, artbear commented
тесты самого правила прекрасно работают

А полные тесты падают из-за проверки текста лицензии, т.к. во всех исходниках 2022 год не заменен на 2023 )

2023-01-17 06:43 UTC, artbear commented
Есть лишние дубли для метаданных, у которых несколько модулей - модуль набора записей и модуль менеджера, например
- возможно, виновато исправление базового класса

![image](https://user-images.githubusercontent.com/2920817/212827871-1d9581ce-9bdf-431c-aa0d-aec9794f5355.png)

2023-01-17 08:19 UTC, asosnoviy requested changes
выключено по умолчанию

2023-01-17 16:24 UTC, artbear commented
> Есть лишние дубли для метаданных, у которых несколько модулей - модуль набора записей и модуль менеджера, например
> 
> * возможно, виновато исправление базового класса

Дублирование результатов исправлено

2023-01-17 16:24 UTC, artbear commented
> выключено по умолчанию

да. выключил правило по умолчанию

2023-03-21 10:18 UTC, nixel2007 requested changes

2023-03-21 10:18 UTC, nixel2007 commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/utils/MdoReferences.java
> +/* * This file is a part of BSL Language Server. * * Copyright (c) 2018-2023 * Alexey Sosnoviy <labotamy@gmail.com>, Nikita Fedkin <nixel2007@gmail.com> and contributors * * SPDX-License-Identi
тут что-то не так с переводами строк

2023-03-21 10:18 UTC, nixel2007 commented on src/main/resources/com/github/_1c_syntax/bsl/languageserver/diagnostics/DenyIncompleteValuesDiagnostic_ru.properties
> +diagnosticName=Запрет незаполненных значений
не хватает описания где (реквизитов/измерений/etc)

2023-03-22 16:36 UTC, artbear commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/utils/MdoReferences.java
> +/* * This file is a part of BSL Language Server. * * Copyright (c) 2018-2023 * Alexey Sosnoviy <labotamy@gmail.com>, Nikita Fedkin <nixel2007@gmail.com> and contributors * * SPDX-License-Identi
Переводы строк исправлены

2023-03-22 16:36 UTC, artbear commented on src/main/resources/com/github/_1c_syntax/bsl/languageserver/diagnostics/DenyIncompleteValuesDiagnostic_ru.properties
> +diagnosticName=Запрет незаполненных значений
Исправил имя правила в ресурсах на "Запрет незаполненных значений у измерений регистров"

2023-03-22 17:16 UTC, nixel2007 commented
Да, как-то так.

ср, 22 мар. 2023 г., 19:19 Artur Ayukhanov ***@***.***>:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In
> src/main/resources/com/github/_1c_syntax/bsl/languageserver/diagnostics/DenyIncompleteValuesDiagnostic_ru.properties
> <https://github.com/1c-syntax/bsl-language-server/pull/2976#discussion_r1145093700>
> :
>
> > @@ -0,0 +1,2 @@
> +diagnosticMessage=Не указан флаг "Запрет незаполненных значений" у измерения "%s" метаданного "%s"
> +diagnosticName=Запрет незаполненных значений
>
> не хватает описания где (реквизитов/измерений/etc)
>
> предлагаешь дополнить имя правила "Запрет незаполненных значений"
>
> например, до "Запрет незаполненных значений у измерений регистров", да?
>
> если да, я согласен, сделаю.
> если нет, поясни.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/1c-syntax/bsl-language-server/pull/2976#discussion_r1145093700>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAIUSKEDKEK6EXPSNY3G3G3W5MRC5ANCNFSM6AAAAAAT5DVFHA>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2023-03-26 12:24 UTC, artbear commented
@nixel2007 Все замечания исправлены, тесты зеленые. Правило готово и ждем приема ПР!

2023-03-29 13:42 UTC, theshadowco commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/utils/MdoReferences.java
> +public class MdoReferences {
джавадоки ?

2023-03-30 11:57 UTC, artbear commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/utils/MdoReferences.java
> +public class MdoReferences {
> джавадоки ?

javadoc добавлены.

2023-03-30 11:58 UTC, artbear commented
@nixel2007 @theshadowco  Все замечания исправлены, тесты зеленые. Правило готово, жду приема ПР!

2023-03-30 18:54 UTC, theshadowco commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/utils/MdoReferences.java
> +    return names[0].concat(".").concat(names[1]);
добавить проверку на пустую ссылку (getMdoReference.isEmpty), иначе упадет

2023-03-30 18:54 UTC, theshadowco commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/utils/MdoReferences.java
> +    return names[0].concat(".").concat(names[1]);
ну или на количество элементов в names

2023-03-30 18:55 UTC, theshadowco commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/utils/MdoReferences.java
> +    return names[0].concat(".").concat(names[1]);
`Некторые разработчики ошибаются, не проверяя количество элементов в массиве...` :)

2023-03-31 16:57 UTC, artbear commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/utils/MdoReferences.java
> +    return names[0].concat(".").concat(names[1]);
@theshadowco я добавил проверку
```java
    if (names.length <= 1){
      return "";
    }
```

2023-04-01 11:22 UTC, nixel2007 commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/utils/MdoReferences.java
> +public class MdoReferences {
А зачем ещё один класс, если уже есть MdoRefBuilder?

2023-04-01 11:23 UTC, nixel2007 commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/utils/MdoReferences.java
> +public class MdoReferences {
https://github.com/1c-syntax/bsl-language-server/blob/feae5606f0de15762dac910e8a0af6815bfbba38/src/main/java/com/github/_1c_syntax/bsl/languageserver/utils/MdoRefBuilder.java

Он ещё и со стринг интернером

2023-04-01 11:26 UTC, nixel2007 commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/utils/MdoReferences.java
> +    if (documentContext.getServerContext().getConfiguration().getScriptVariant() == ScriptVariant.ENGLISH) {
Мне казалось, этот хелпер уже реализован в самом mdclasses

2023-06-17 08:55 UTC, artbear commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/utils/MdoReferences.java
> +    if (documentContext.getServerContext().getConfiguration().getScriptVariant() == ScriptVariant.ENGLISH) {
@nixel2007 
я только что проверил поиском Гитхаба по mdclasses, в нем
- единственное использование getScriptVariant есть в интерфейсе CF
- и нет какой-то проверки на английский вариант или что-то подобное

так что такого хелпера нет

Предлагаю закрыть замечание. жду комментариев.

/cc @TheShadoWCo

2023-06-17 09:03 UTC, artbear commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/utils/MdoReferences.java
> +public class MdoReferences {
Перенес методы из MdoReferences  в существующий класс MdoRefBuilder
- и добавил использование стринг интернера

2023-06-17 09:53 UTC, artbear commented
@nixel2007 @theshadowco Все замечания исправлены, тесты зеленые. Правило готово, жду приема ПР!

2023-06-18 15:10 UTC, merged