close #3042 Двойная запись в ЖР в диагностике UsageWriteLogEvent
1c-syntax/bsl-language-server pull request #3043
Opened 2023-04-24 04:10 UTC by kuzyara

## Описание
https://github.com/1c-syntax/bsl-language-server/issues/3042
Добавил примеров по ишузу #3042

Просто текст в docs/diagnostics/UsageWriteLogEvent.md

2023-04-24 06:14 UTC, nixel2007 commented
Кажется, для новых правильрых вариантов надо доработать диагностику, разве нет?

2023-04-24 07:48 UTC, artbear requested changes
Неожиданно много замечаний.

2023-04-24 07:48 UTC, artbear commented on docs/diagnostics/UsageWriteLogEvent.md
> +        ЗаписьЖурналаРегистрации(
что за странная строка кода `ЗаписьЖурналаРегистрации(` ??

Предлагаю заменить на нормальный вариант вызова метода с записью подробного представления ошибки

2023-04-24 07:48 UTC, artbear commented on docs/diagnostics/UsageWriteLogEvent.md
> +        ВызватьИсключение "Не удалось записать настройки ""Яндекс"" по причине" + Инфо;
В целом, данный пример плохой и не имеет отношения к двойной записи в ЖР !
- нет записи в ЖР подробного представления
- зачем-то выдается какая-то другая ошибка - и тогда где тут двойная запись в ЖР одной и той же ошибки
- почему-то объект Инфо сериализуется в строку, что также неверно.

2023-04-24 07:48 UTC, artbear commented on docs/diagnostics/UsageWriteLogEvent.md
> +В общем случае не рекомендуется перехватывать исключения. В частности не нужно перехватывать исключения только ради выдачи сообщения об ошибке. Необработанное исключение в любом случае будет записано
1 странное высказывание "Необработанное исключение в любом случае будет записано в журнал регистрации, если исключение возникло на сервере."

читается так - "исключение на клиенте не будет перехвачено", а это неверно.

2 >В частности не нужно перехватывать исключения только ради выдачи сообщения об ошибке.

С этим высказыванием я также не согласен. 
В некоторых случаях полезно добавить контекст\дополнение к стандартному представлению ошибки, например, можно расшифровать проблему и добавить ее в ЖР вместе с подробным представлением ошибки для более точной отработки ошибки администраторами системы.

2023-04-24 07:48 UTC, artbear commented on docs/diagnostics/UsageWriteLogEvent.md
> +При вызове методов `ВызватьИсключение;` и `ЗаписьЖурналаРегистрации` необходимо соблюдать определённый порядок, не допускающий двойной записи текста ошибки в журнал регистрации.
здесь указана строка `ВызватьИсключение;`, а в примере ниже она не используется, что неверно.

2023-04-24 07:48 UTC, artbear commented on docs/diagnostics/UsageWriteLogEvent.md
> +Одновременная запись в ЖР и вызов исключения возможны при пробросе исключения на клиент, где нет записи в ЖР).
лишняя скобка в конце предложения

2023-04-24 07:48 UTC, artbear commented on docs/diagnostics/UsageWriteLogEvent.md
> +Таким образом, либо проброс исключения в верхнеуровневую попытку без записи в ЖР:
Предложение предлагает решение, хотя выше по тексту в текущем разделе не указана проблема.

Предлагаю так
- `Следовательно правильно выполнять либо проброс исключения в верхнеуровневую попытку без записи в ЖР:`

2023-04-24 07:48 UTC, artbear commented on docs/diagnostics/UsageWriteLogEvent.md
> +либо передача текста ошибки:
исправить на "либо передачу подробного представления текста ошибки" (правильный падеж и подробного)

2023-04-24 07:48 UTC, artbear commented on docs/diagnostics/UsageWriteLogEvent.md
> +		Возврат ТекстОшибки;
неверный отступ перед Возврат

2023-04-24 07:48 UTC, artbear commented on docs/diagnostics/UsageWriteLogEvent.md
> +<img src="https://user-images.githubusercontent.com/2604430/233899417-7d7a5d69-db80-494c-9266-f4cff6a2fcc2.png"  width="40%"> <img src="https://user-images.githubusercontent.com/2604430/233899454-8a3
неверные картинки.
- нужно их приложить в каталог документации, а не выкладывать ссылки на гитхаб

2023-04-24 07:48 UTC, artbear commented on docs/diagnostics/UsageWriteLogEvent.md
> +## Двойная запись в журнал регистрации
добавлено 3 раздела с "##" - это один и тот же уровень. разве это верно?

2023-04-24 11:34 UTC, kuzyara commented on docs/diagnostics/UsageWriteLogEvent.md
> +        ВызватьИсключение "Не удалось записать настройки ""Яндекс"" по причине" + Инфо;
```1c
&НаСервере
Процедура ПриЗаписиНаСервере(Отказ, ТекущийОбъект, ПараметрыЗаписи)
	// ...
	Попытка 
		МенеджерЗаписи.Записать();
	Исключение
		Отказ = Истина;
		ТекстОшибки = ПодробноеПредставлениеОшибки(ИнформацияОбОшибке());
		ЗаписьЖурналаРегистрации(
			"Запись справочника Филиалы",
			УровеньЖурналаРегистрации.Ошибка,
			Метаданные.Справочники.Филиалы,
			ТекущийОбъект.Ссылка,
			ТекстОшибки);
		ВызватьИсключение "Не удалось записать настройки ""Яндекс"" по причине" + ТекстОшибки;
	КонецПопытки;
```

> * и тогда где тут двойная запись в ЖР одной и той же ошибки

Можно ли делать вызов исключения для дополнения текста ошибки?

2023-04-24 11:46 UTC, kuzyara commented on docs/diagnostics/UsageWriteLogEvent.md
> +        ВызватьИсключение "Не удалось записать настройки ""Яндекс"" по причине" + Инфо;
![image](https://user-images.githubusercontent.com/2604430/233987010-8579c06f-78df-4ecd-9d43-b88ba076d97f.png)

> никогда не используйте `ВызватьИсключение Текст` для дополнения текста ошибки. 

Правильно ли я понял ваши слова?

2023-04-24 14:50 UTC, artbear commented on docs/diagnostics/UsageWriteLogEvent.md
> +        ВызватьИсключение "Не удалось записать настройки ""Яндекс"" по причине" + Инфо;
>"никогда не используйте ВызватьИсключение Текст для дополнения текста ошибки. "
Правильно ли я понял ваши слова?

в приведенном комментария я все-таки написал "без веских причин никогда не используйте ..." 
т.е. иногда все-таки можно, если очень нужно )
и показал, почему такой вариант может быть плохим!

2023-04-24 14:53 UTC, artbear commented on docs/diagnostics/UsageWriteLogEvent.md
> +        ВызватьИсключение "Не удалось записать настройки ""Яндекс"" по причине" + Инфо;
> Пример косвенный, да. Но часто встречаемый.
> 
> Можно ли делать вызов исключения для дополнения текста ошибки? Корректен ли этот код? Глаз не режет?

Все-таки так себе пример, честно.
я в "том самом комментарии", что на скриншоте, приводил аргументы, почему вызов исключения с параметрами может быть плох

хорошо бы об этом также написать, если уж решили приводить такой сложный пример.

2023-04-25 06:52 UTC, kuzyara commented on docs/diagnostics/UsageWriteLogEvent.md
> +        ВызватьИсключение "Не удалось записать настройки ""Яндекс"" по причине" + Инфо;
извините, я побуду занудой, попробую эти расплывчатые формулировки объяснить на примерах.

что я понял.
1. `ВызватьИсключение КакойТоТекст;` - например `ВызватьИсключение "Не удалось получить значение реквизита"` - так прокидывать исключения нельзя, ок, это понятно - теряется стек.

2. `ВызватьИсключение КакойТоТекст + ОписаниеОшибки();` - неправильно, так как теряется код на каком же выражении возникла реальная ошибка, видна только строка, где возникло исключение

`ВызватьИсключение "Не удалось выполнить операцию по причине: " + ОписаниеОшибки();`
выведет
```1c
// Не удалось выполнить операцию по причине: {ВнешняяОбработка.ВнешняяОбработка1.Форма.Форма.Форма(158)}: Деление на 0
// {ВнешняяОбработка.ВнешняяОбработка1.Форма.Форма.Форма(160)}:ВызватьИсключение "Не удалось выполнить операцию по причине: " + ОписаниеОшибки();
// {ВнешняяОбработка.ВнешняяОбработка1.Форма.Форма.Форма(166)}:ТестОписаниеОшибкиНаСервере();
```
а просто `ВызватьИсключение;` без параметров выведет:
```bls
// Деление на 0
// {ВнешняяОбработка.ВнешняяОбработка1.Форма.Форма.Форма(158)}:А = 1/0;
// {ВнешняяОбработка.ВнешняяОбработка1.Форма.Форма.Форма(166)}:ТестОписаниеОшибкиНаСервере();
```
То есть `ОписаниеОшибки()` в данном случае не содержит строки кода `А = 1/0;`. Это понятно.

3. > иногда все-таки можно, если очень нужно )

вот здесь я не понял: когда можно и какой критерий у нужно. 

Как говорит Торвальдс: “Talk is cheap. Show me the code.” ;)

2023-04-25 07:04 UTC, kuzyara commented on docs/diagnostics/UsageWriteLogEvent.md
> +        ВызватьИсключение "Не удалось записать настройки ""Яндекс"" по причине" + Инфо;
дело в том, что я самого начала работы с 1с не имел четкого понимания работы с исключениями, и вот по прошествии многих лет наконец-то начали вырисовываться какие-то шаблоны, хотелось бы дойти до определённых правил (с примерами).

2023-04-25 08:21 UTC, kuzyara commented
![image](https://user-images.githubusercontent.com/2604430/234215120-170e8dae-9f09-4ff2-b311-bd04b9a4430c.png)

Как говориться, у каждого правила есть исключение.
Вот пример когда можно использовать `ВызватьИсключение КакойТоТекст + КраткоеПредставлениеОшибки();`
То есть когда мы перехватываем исключения, которые сами и создали (за пределами секции Попытка-Исключение-КонецПопытки).
```1c
Процедура ПроверитьПараметрыАдминистрирования(Знач ПараметрыАдминистрированияКластера, Знач ПараметрыАдминистрированияИБ = Неопределено,
	ПроверятьПараметрыАдминистрированияИнформационнойБазы = Истина,
	ПроверятьПараметрыАдминистрированияКластера = Истина) Экспорт
	
	Если ПроверятьПараметрыАдминистрированияКластера ИЛИ ПроверятьПараметрыАдминистрированияИнформационнойБазы Тогда
		
		Попытка
			COMСоединитель = COMСоединитель();
			
			СоединениеСАгентомСервера = СоединениеСАгентомСервера(COMСоединитель,
				ПараметрыАдминистрированияКластера.АдресАгентаСервера,
				ПараметрыАдминистрированияКластера.ПортАгентаСервера);
			
			Кластер = ПолучитьКластер(СоединениеСАгентомСервера,
				ПараметрыАдминистрированияКластера.ПортКластера,
				ПараметрыАдминистрированияКластера.ИмяАдминистратораКластера,
				ПараметрыАдминистрированияКластера.ПарольАдминистратораКластера);
		Исключение
			Если ОбщегоНазначения.ЭтоWindowsСервер() Тогда 
				ТекстИсключения = СтроковыеФункцииКлиентСервер.ПодставитьПараметрыВСтроку(
					НСтр("ru = 'Не удалось подключиться с компьютера %1 к кластеру серверов по причине:
						|%2
						|
						|Если в тексте ошибки указано, что ""класс не зарегистрирован"" или не совпадает версия компоненты ""comcntr"" с требуемой,
						|то следует зарегистрировать ее на компьютере %1, для этого обратитесь к администратору.'"),
					ИмяКомпьютера(), КраткоеПредставлениеОшибки(ИнформацияОбОшибке()));
			Иначе 
				ТекстИсключения = СтроковыеФункцииКлиентСервер.ПодставитьПараметрыВСтроку(
					НСтр("ru = 'Не удалось подключиться с компьютера %1 к кластеру серверов по причине:
						|%2.'"),
					ИмяКомпьютера(), КраткоеПредставлениеОшибки(ИнформацияОбОшибке()));
			КонецЕсли;
			
			ВызватьИсключение ТекстИсключения
			
		КонецПопытки;
		
	КонецЕсли;
	
	// ...	
#КонецОбласти

#Область СлужебныеПроцедурыИФункции

Функция COMСоединитель()
	
	Если БезопасныйРежим() <> Ложь Тогда
		ВызватьИсключение НСтр("ru = 'Администрирование кластера невозможно в безопасном режиме'");
	КонецЕсли;
	
	Если ОбщегоНазначения.РазделениеВключено() Тогда
		ВызватьИсключение НСтр("ru = 'В модели сервиса недопустимо выполнение прикладной информационной базой функций администрирования кластера'");
	КонецЕсли;
	
	Возврат Новый COMОбъект(ОбщегоНазначенияКлиентСервер.ИмяCOMСоединителя());
	
КонецФункции

Функция СоединениеСАгентомСервера(COMСоединитель, Знач АдресАгентаСервера, Знач ПортАгентаСервера)
	
	СтрокаСоединенияСАгентомСервера = "tcp://" + АдресАгентаСервера + ":" + Формат(ПортАгентаСервера, "ЧГ=0");
	СоединениеСАгентомСервера = COMСоединитель.ConnectAgent(СтрокаСоединенияСАгентомСервера);
	Возврат СоединениеСАгентомСервера;
	
КонецФункции

Функция ПолучитьКластер(СоединениеСАгентомСервера, Знач ПортКластера, Знач ИмяАдминистратораКластера, Знач ПарольАдминистратораКластера)
	
	Для Каждого Кластер Из СоединениеСАгентомСервера.GetClusters() Цикл
		Если Кластер.MainPort = ПортКластера Тогда
			СоединениеСАгентомСервера.Authenticate(Кластер, ИмяАдминистратораКластера, ПарольАдминистратораКластера);
			Возврат Кластер;
		КонецЕсли;
	КонецЦикла;
	
	ВызватьИсключение СтроковыеФункцииКлиентСервер.ПодставитьПараметрыВСтроку(НСтр("ru = 'На рабочем сервере %1 не существует кластер %2'"),
		СоединениеСАгентомСервера.ConnectionString,
		ПортКластера);
	
КонецФункции
```

пишу этот код для себя, так как коллекционирую шаблоны работы с исключениями.

![image](https://user-images.githubusercontent.com/2604430/234217746-494dd9b4-6bee-430b-8471-5fe9e3bb15f7.png)

2023-04-25 08:31 UTC, kuzyara commented
пример из типовой, когда дублируются ошибки в ЖР
```bsl
// Помечает на удаление все задачи указанного бизнес-процесса (или снимает отметку).
//
// Параметры:
//  БизнесПроцессСсылка - ОпределяемыйТип.БизнесПроцесс - бизнес-процесс, задачи которого нужно пометить на удаление.
//  ПометкаУдаления     - Булево - значение свойства ПометкаУдаления для задач.
//
Процедура УстановитьПометкуУдаленияЗадач(БизнесПроцессСсылка, ПометкаУдаления) Экспорт
	
	ПредставлениеСсылки = Строка(БизнесПроцессСсылка);
	
	НачатьТранзакцию();
	Попытка
		Блокировка = Новый БлокировкаДанных;
		ЭлементБлокировки = Блокировка.Добавить("Задача.ЗадачаИсполнителя");
		ЭлементБлокировки.УстановитьЗначение("БизнесПроцесс", БизнесПроцессСсылка);
		Блокировка.Заблокировать();
		
		Запрос = Новый Запрос("ВЫБРАТЬ
			|	Задачи.Ссылка КАК Ссылка 
			|ИЗ
			|	Задача.ЗадачаИсполнителя КАК Задачи
			|ГДЕ
			|	Задачи.БизнесПроцесс = &БизнесПроцесс");
		Запрос.УстановитьПараметр("БизнесПроцесс", БизнесПроцессСсылка);
		Выборка = Запрос.Выполнить().Выбрать();
		
		Пока Выборка.Следующий() Цикл
			ЗадачаОбъект = Выборка.Ссылка.ПолучитьОбъект();
			ЗадачаОбъект.УстановитьПометкуУдаления(ПометкаУдаления);
		КонецЦикла;
		
		ЗафиксироватьТранзакцию();
	Исключение
		ОтменитьТранзакцию();
		ЗаписьЖурналаРегистрации(СобытиеЖурналаРегистрации(), УровеньЖурналаРегистрации.Ошибка, 
			БизнесПроцессСсылка.Метаданные(), ПредставлениеСсылки, ПодробноеПредставлениеОшибки(ИнформацияОбОшибке()));
		ВызватьИсключение;
	КонецПопытки;
	
КонецПроцедуры

// Обработчик подписки на событие УстановитьПометкуУдаленияЗадач.
//
Процедура УстановитьПометкуУдаленияЗадач(Источник, Отказ) Экспорт
	
	Если Источник.ОбменДанными.Загрузка Тогда 
        Возврат;  
	КонецЕсли; 
	
	Если Источник.ЭтоНовый() Тогда 
        Возврат;  
	КонецЕсли; 
	
	ПредыдущаяПометкаУдаления = ОбщегоНазначения.ЗначениеРеквизитаОбъекта(Источник.Ссылка, "ПометкаУдаления");
	Если Источник.ПометкаУдаления <> ПредыдущаяПометкаУдаления Тогда
		УстановитьПривилегированныйРежим(Истина);
		БизнесПроцессыИЗадачиСервер.УстановитьПометкуУдаленияЗадач(Источник.Ссылка, Источник.ПометкаУдаления);
	КонецЕсли;	
	
КонецПроцедуры
```

2023-05-24 04:41 UTC, closed without merging