Новая диагностика "Зарезервированные имена параметров"
1c-syntax/bsl-language-server pull request #3187
Opened 2023-11-23 06:22 UTC by AlexPCRus

## Описание
Добавлена новая диагностика, проверяющая совпадение имен параметров методов с именами системных перечислений и т.п., задающихся списком

## Связанные задачи

## Чеклист

### Общие

- [+] Ветка PR обновлена из develop
- [+] Отладочные, закомментированные и прочие, не имеющие смысла участки кода удалены
- [+] Изменения покрыты тестами
- [+] Обязательные действия перед коммитом выполнены (запускал команду `gradlew precommit`)

### Для диагностик

- [+] Описание диагностики заполнено для обоих языков (присутствуют файлы для обоих языков, для русского заполнено все подробно, перевод на английский можно опустить)

## Дополнительно

2023-11-23 06:28 UTC, nixel2007 commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/ReservedParameterNamesDiagnostic.java
> +  type = DiagnosticType.CODE_SMELL,
Это точно code smell? Не bug?

2023-11-23 06:30 UTC, nixel2007 commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/ReservedParameterNamesDiagnostic.java
> +  private Pattern reservedWords = CaseInsensitivePattern.compile(RESERVED_WORDS_DEFAULT);
Возможно стоит добавить защитные ^ и $ в итоговую регулярку, чтобы исключить срабатывания на параметрах содержащих системное перечисление как часть имени

2023-11-23 06:31 UTC, nixel2007 commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/ReservedParameterNamesDiagnostic.java
> +      while (matcher.find()) {
Кажется, здесь можно обойтись без цикла

2023-11-23 06:33 UTC, nixel2007 commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/ReservedParameterNamesDiagnostic.java
> +        diagnosticStorage.addDiagnostic(parameter.getRange(), info.getResourceString("reservedWordMessage", parameter.getName()));
Если переименовать ключ ресурса в diagnosticMessage, то можно будет дёргать хелпер info.getMessage(Object...args)

2023-11-23 06:34 UTC, nixel2007 commented on src/main/resources/com/github/_1c_syntax/bsl/languageserver/diagnostics/ReservedParameterNamesDiagnostic_en.properties
> +diagnosticMessage=Reserved name found as parameter name.
А, он тут уже есть. Ну вот его и можно использовать, а второй параметр убрать.

2023-11-23 06:35 UTC, nixel2007 commented on src/main/resources/com/github/_1c_syntax/bsl/languageserver/diagnostics/ReservedParameterNamesDiagnostic_ru.properties
> +reservedWordMessage=Необходимо переименовать параметр "%s", совпадающий с зарезервированным словом
Убрать паразитное "необходимо", "переименовать" перевести в повелительную форму

2023-11-23 06:36 UTC, nixel2007 commented on src/test/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/ReservedParameterNamesTest.java
> +    assertThat(diagnostics, true)
Не хватает пары негативных тест-кейсов, чтобы поймать простейшие FP

2023-11-23 06:36 UTC, AlexPCRus commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/ReservedParameterNamesDiagnostic.java
> +  type = DiagnosticType.CODE_SMELL,
Я типы скопировал :) Предложения приветствуются.

2023-11-23 08:39 UTC, AlexPCRus commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/ReservedParameterNamesDiagnostic.java
> +      while (matcher.find()) {
Исправлено

2023-11-23 08:39 UTC, AlexPCRus commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/ReservedParameterNamesDiagnostic.java
> +        diagnosticStorage.addDiagnostic(parameter.getRange(), info.getResourceString("reservedWordMessage", parameter.getName()));
Заменил на getMessage

2023-11-23 08:40 UTC, AlexPCRus commented on src/main/resources/com/github/_1c_syntax/bsl/languageserver/diagnostics/ReservedParameterNamesDiagnostic_en.properties
> +diagnosticMessage=Reserved name found as parameter name.
Начал использовать

2023-11-23 08:40 UTC, AlexPCRus commented on src/main/resources/com/github/_1c_syntax/bsl/languageserver/diagnostics/ReservedParameterNamesDiagnostic_ru.properties
> +reservedWordMessage=Необходимо переименовать параметр "%s", совпадающий с зарезервированным словом
Изменил текст диагностического сообщения

2023-11-23 08:40 UTC, AlexPCRus commented on src/test/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/ReservedParameterNamesTest.java
> +    assertThat(diagnostics, true)
Добавил негативные тесты

2023-11-23 08:41 UTC, AlexPCRus commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/ReservedParameterNamesDiagnostic.java
> +  private Pattern reservedWords = CaseInsensitivePattern.compile(RESERVED_WORDS_DEFAULT);
Добавил

2023-11-23 16:28 UTC, artbear commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/ReservedParameterNamesDiagnostic.java
> +  @DiagnosticParameter(type = String.class)
не хватает подсказки к параметру

2023-11-23 16:30 UTC, artbear commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/ReservedParameterNamesDiagnostic.java
> +                       + "$");
при таком коде сборки регулярки будет ошибка при вводе пустого шаблона, в котором, например, один пробел.

предлагаю добавить ^ и $ при условии, что переданный шаблон не пуст

2023-11-23 16:32 UTC, artbear commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/ReservedParameterNamesDiagnostic.java
> +    if (reservedWords.pattern().isBlank()) {
зачем для всех методов проверяемой конфигурации проверять наличие пустого шаблона? это же бесполезно.

предлагаю проверять где-то уровнем выше, например, для всего модуля\файла, так будет производительнее.

2023-11-23 22:40 UTC, AlexPCRus commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/ReservedParameterNamesDiagnostic.java
> +    if (reservedWords.pattern().isBlank()) {
Перенес проверку выше

2023-11-23 22:40 UTC, AlexPCRus commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/ReservedParameterNamesDiagnostic.java
> +                       + "$");
добавил удаление пробелов, написал тест

2023-11-24 05:58 UTC, artbear commented on src/main/java/com/github/_1c_syntax/bsl/languageserver/diagnostics/ReservedParameterNamesDiagnostic.java
> +    if (reservedWords.pattern().isBlank()) {
решено

2023-11-24 06:00 UTC, artbear requested changes

2023-11-24 06:00 UTC, artbear commented on docs/diagnostics/ReservedParameterNames.md
> +Имя параметра не должно совпадать с именами системных перечислений.
1 Не хватает ссылок на источник. Какой все-таки стандарт используется

2 не хватает описания проблемы, решаемой правилом.

2023-11-30 08:47 UTC, artbear requested changes

2023-11-30 08:47 UTC, artbear commented on docs/diagnostics/ReservedParameterNames.md
> +Если имя параметра совпадает с именем системного перечисления, то в локальном контексте доступ к значениям этого перечисления будет недоступен.
тавтология и не звучит - доступ к значениям этого перечисления будет недоступен

предлагаю заменить на "невозможно будет обратиться к значениям этого системного перечисления, потому что параметр скрывает это системное перечисление"

2023-11-30 08:47 UTC, artbear commented on src/main/resources/com/github/_1c_syntax/bsl/languageserver/diagnostics/ReservedParameterNamesDiagnostic_ru.properties
> +diagnosticMessage=Переименуйте параметр "%s" чтобы он не совпадал с зарезервированным словом.
перед "чтобы" нужна запятая

2023-12-14 03:42 UTC, theshadowco approved these changes

2024-06-04 06:15 UTC, theshadowco approved these changes

2024-07-10 17:47 UTC, theshadowco commented
/rebase

2024-11-04 16:44 UTC, merged